In [25]:
import numpy as np
import pandas as pd

In [26]:
df_pmmap = pd.read_csv("../../data/a1/PM_map.csv")

In [ ]:
# df_pmmap

,รหัสสถานี,ชื่อสถานี,รายละเอียดจุดติดตั้งสถานี,english_name
0,02T,แขวงหิรัญรูจี เขตธนบุรี กทม.,มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา,Bangkok Metropolis
1,05T,แขวงบางนา เขตบางนา กทม.,กรมอุตุนิยมวิทยา,Bangkok Metropolis
2,10T,แขวงคลองจั่น เขตบางกะปิ กทม.,เคหะชุมชนคลองจั่น,Bangkok Metropolis
3,11T,แขวงดินแดง เขตดินแดง กทม.,สนามกีฬาเคหะชุมชนห้วยขวาง,Bangkok Metropolis
4,12T,แขวงช่องนนทรี เขตยานนาวา กทม.,โรงเรียนนนทรีวิทยา,Bangkok Metropolis
5,59T,แขวงพญาไท เขตพญาไท กทม.,กรมประชาสัมพันธ์,Bangkok Metropolis
6,61T,แขวงพลับพลา เขตวังทองหลาง กทม.,โรงเรียนบดินทรเดชา (สิงห์ สิงหเสนี),Bangkok Metropolis
7,03T,ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.,ริมถนนกาญจนาภิเษก,Bangkok Metropolis
8,50T,ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.,โรงพยาบาลจุฬาลงกรณ์,Bangkok Metropolis
9,52T,ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.,สถานีไฟฟ้าย่อยธนบุรี,Bangkok Metropolis
10,53T,ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.,สถานีตำรวจนครบาลโชคชัย,Bangkok Metropolis
11,54T,ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.,เคหะชุมชนดินแดง,Bangkok Metropolis
12,08T,ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ,ศูนย์ฟื้นฟูอาชีพคนพิการและทุพพลภาพพระประแดง,Samut Prakan
13,16T,ต.บางโปรง อ.เมือง จ.สมุทรปราการ,โรงไฟฟ้าพระนครใต้,Samut Prakan
14,17T,ต.ตลาด อ.พระประแดง จ.สมุทรปราการ,บ้านพักกรมอุตสาหกรรมพื้นฐานและการเหมืองแร่,Samut Prakan
15,18T,ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ,ศาลากลางจังหวัดสมุทรปราการ,Samut Prakan
16,19T,ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ,เคหะชุมชนเมืองใหม่บางพลี,Samut Prakan
17,13T,ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี,กรมควบคุมโรค,Nonthaburi
18,22T,ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี,มหาวิทยาลัยสุโขทัยธรรมาธิราช,Nonthaburi
19,14T,ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร,หน่วยบริการตำรวจทางหลวงศรีสำราญ สมุทรสาคร,Samut Sakhon
20,27T,ต.มหาชัย อ.เมือง จ.สมุทรสาคร,โรงเรียนสมุทรสาครวิทยาลัย,Samut Sakhon
21,20T,ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี,มหาวิทยาลัยกรุงเทพ (วิทยาเขตรังสิต),Pathum Thani
22,81T,ต.นครปฐม อ.เมือง จ.นครปฐม,อ่างเก็บน้ำประปา นครปฐม,Nakhon Pathom
23,21T,ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา,โรงเรียนอยุธยาวิทยาลัย,Phra Nakhon Si Ayutthaya
24,24T,ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี,สถานีตำรวจภูธรตำบลหน้าพระลาน,NaN
25,25T,ต.ปากเพรียว อ.เมือง จ.สระบุรี,สถานีดับเพลิงพระลักษณ์,NaN
26,26T,ต.หน้าเมือง อ.เมือง จ.ราชบุรี,สำนักงานสิ่งแวดล้อมภาคที่ ๘ ราชบุรี,Ratchaburi
27,79T,ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี,สถานีอุตุนิยมวิทยากาญจนบุรี,Kanchanaburi
28,84T,ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม,สำนักงานสาธารณสุขจังหวัดสมุทรสงคราม,Samut Songkhram
29,85T,ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี,สนามกีฬากลางจังหวัดสุพรรณบุรี,Suphan Buri
30,99T,ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี,สถานีอุตุนิยมวิทยาลพบุรี,Lop Buri
31,103T,ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์,สถานีตรวจอากาศหัวหิน สถานีอุตุนิยมวิทยาประจวบค...,Prachuap Khiri Khan
32,104T,ต.บางมัญ อ.เมือง จ.สิงห์บุรี,โรงเรียนสิงห์บุรี,Sing Buri
33,46T,ต.ในเมือง อ.เมือง จ.ขอนแก่น,ส่วนอุทกวิทยา สำนักงานทรัพยากรน้ำภาค ๔ ขอนแก่น,Khon Kaen
34,47T,ต.ในเมือง อ.เมือง จ.นครราชสีมา,สถานีสูบน้ำเสียที่ ๑ ห้าแยกไอที นครราชสีมา,Nakhon Ratchasima
35,72T,ต.กุดป่อง อ.เมือง จ.เลย,สวนสาธารณะเฉลิมพระเกียรติ 60 พรรษา มหาราชินี,Loei
36,82T,ต.มีชัย อ.เมือง จ.หนองคาย,สวนสาธารณะหนองถิ่น,Nong Khai
37,83T,ต.ในเมือง อ.เมือง จ.อุบลราชธานี,ศูนย์แสดงและจำหน่ายสินค้า OTOP จังหวัดอุบลราชธานี,Ubon Ratchathani
38,88T,ต.ในเมือง อ.เมือง จ.นครพนม,สถานีอุตุนิยมวิทยานครพนม,Nakhon Phanom
39,90T,ต.ธาตุนาเวง อ.เมือง จ.สกลนคร,สถานีอุตุนิยมวิทยาสกลนคร,Sakon Nakhon
40,91T,ต.หมากแข้ง อ.เมือง จ.อุดรธานี,บริเวณสวนสาธารณะหนองประจักษ์,Udon Thani
41,101T,ต.เสม็ด อ.เมือง จ.บุรีรัมย์,ศาลากลางจังหวัดบุรีรัมย์,Buri Ram
42,102T,ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร,สนามกีฬากลางจังหวัดมุกดาหาร,Mukdahan
43,106T,ต.บึงกาฬ อ.เมือง จ.บึงกาฬ,สวนสาธารณะหนองบึงกาฬ,Bueng Kan
44,107T,ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์,สวนสาธารณะดอนกลาง,Kalasin
45,108T,ต.ในเมือง อ.เมือง จ.ชัยภูมิ,สนามกีฬาเทศบาลเมืองชัยภูมิ,Chaiyaphum
46,109T,ต.ในเมือง อ.เมือง จ.ยโสธร,สวนสาธารณะพญาแถน,Yasothon
47,110T,ต.บุ่ง อ.เมือง จ.อำนาจเจริญ,สำนักงานเทศบาลเมืองอำนาจเจริญ,Amnat Charoen
48,111T,ต.นอกเมือง อ.เมือง จ.สุรินทร์,สถานีอุตุนิยมวิทยาสุรินทร์,Surin
49,112T,ต.หนองครก อ.เมือง จ.ศรีสะเกษ,สถานีอุตุนิยมวิทยาศรีสะเกษ,Si Sa Ket
50,28T,ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง,สำนักงานสาธารณสุขอำเภอปลวกแดง,Rayong
51,29T,ต.มาบตาพุด อ.เมือง จ.ระยอง,โรงพยาบาลส่งเสริมสุขภาพตำบลมาบตาพุด,Rayong
52,30T,ต.ท่าประดู่ อ.เมือง จ.ระยอง,สำนักงานเกษตรจังหวัดระยอง,Rayong
53,31T,ต.ห้วยโป่ง อ.เมือง จ.ระยอง,ศูนย์วิจัยพืชไร่ระยอง,Rayong
54,74T,ต.เนินพระ อ.เมือง จ.ระยอง,ศูนย์ราชการจังหวัดระยอง,Rayong
55,32T,ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี,สนามกีฬาเทศบาลแหลมฉบัง,Chon Buri
56,33T,ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเขาหิน,Chon Buri
57,34T,ต.บ้านสวน อ.เมือง จ.ชลบุรี,สำนักงานสิ่งแวดล้อมภาคที่ ๑๓ ชลบุรี,Chon Buri
58,60T,ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา,สำนักงานเทศบาลตำบลทุ่งสะเดา,Chachoengsao
59,71T,ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว,สวนกาญจนาภิเษก ร.9 (ฝั่งสวนหิน),NaN
60,77T,ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี,ศาลาประชาคมบ้านบุยายใบ ปราจีนบุรี,Prachin Buri
61,87T,ต.บางพระ อ.เมือง จ.ตราด,สนามกีฬากลาง จังหวัดตราด,Trat
62,100T,ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี,สถานีอุตุนิยมวิทยาจันทบุรี,Chanthaburi
63,105T,ต.บ้านใหญ่ อ.เมือง จ.นครนายก,สถานีอนามัยเทศบาลเมืองนครนายก,Nakhon Nayok
64,35T,ต.ช้างเผือก อ.เมือง จ.เชียงใหม่,ศูนย์ราชการจังหวัดเชียงใหม่,Chiang Mai
65,36T,ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่,โรงเรียนยุพราชวิทยาลัย,Chiang Mai
66,37T,ต.พระบาท อ.เมือง จ.ลำปาง,สถานีอุตุนิยมวิทยาลำปาง,Lampang
67,38T,ต.สบป้าด อ.แม่เมาะ จ.ลำปาง,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสบป้าด,Lampang
68,39T,ต.บ้านดง อ.แม่เมาะ จ.ลำปาง,โรงพยาบาลส่งเสริมสุขภาพตำบลท่าสี,Lampang
69,40T,ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง,สำนักงานการประปาส่วนภูมิภาคอำเภอแม่เมาะ,Lampang
70,41T,ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์,โครงการชลประทานนครสวรรค์,Nakhon Sawan
71,57T,ต.เวียง อ.เมือง จ.เชียงราย,สำนักงานทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัดเ...,Chiang Rai
72,73T,ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย,สำนักงานสาธารณสุขอำเภอแม่สาย,Chiang Rai
73,58T,ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน,สำนักงานทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัด ...,Mae Hong Son
74,67T,ต.ในเวียง อ.เมือง จ.น่าน,สำนักงานเทศบาลเมืองน่าน,Nan
75,75T,ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน,โรงพยาบาลเฉลิมพระเกียรติ น่าน,Nan
76,68T,ต.บ้านกลาง อ.เมือง จ.ลำพูน,สถานีอุตุนิยมวิทยาลำพูน,Lamphun
77,69T,ต.นาจักร อ.เมือง จ. แพร่,สถานีอุตุนิยมวิทยาแพร่,Phrae
78,70T,ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา,สนามกีฬาจังหวัดพะเยา,Phayao
79,76T,ต.แม่ปะ อ.แม่สอด จ.ตาก,ศูนย์การศึกษานอกระบบอำเภอแม่สอด,Tak
80,86T,ต.ในเมือง อ.เมือง จ.พิษณุโลก,สวนชมน่าน บริเวณหน้าวิทยาลัยอาชีวศึกษาพิษณุโลก,Phitsanulok
81,92T,ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์,บริเวณภายในพื้นที่สวนมหามงคลเฉลิมพระเกียรติพระ...,Uttaradit
82,94T,ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร,ลานอนุรักษ์วัฒนธรรมไทยสิริจิตอุทยาน,Kamphaeng Phet
83,95T,ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร,สนามกีฬาจังหวัดพิจิตร,Phichit
84,96T,ต.ธานี อ.เมือง จ.สุโขทัย,สวนสาธารณะ ชุมชนเลอไทย,Sukhothai
85,97T,ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์,สวนสาธารณะเพชบุระ,Phetchabun
86,98T,ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี,สวนเฉลิมพระเกียรติพระบาทสมเด็จพระเจ้าอยู่หัว เ...,Uthai Thani
87,42T,ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี,สำนักงานสิ่งแวดล้อมภาคที่ ๑๔ สุราษฎร์ธานี,Surat Thani
88,43T,ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต,ศูนย์บริการสาธารณสุขเทศบาลนครภูเก็ต,Phuket
89,44T,ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา,เทศบาลนครหาดใหญ่,Songkhla
90,62T,ต.บางนาค อ.เมือง จ.นราธิวาส,ศาลากลางจังหวัดนราธิวาส,Narathiwat
91,63T,ต.สะเตง อ.เมือง จ.ยะลา,สวนสาธารณะสนามโรงพิธีช้างเผือก ยะลา,Yala
92,78T,ต.เบตง อ.เบตง จ.ยะลา,ศูนย์พัฒนาเด็กเล็กเทศบาลเมืองเบตง,Yala
93,80T,ต.พิมาน อ.เมือง. จ.สตูล,ศาลากลางจังหวัดสตูล,Satun
94,89T,ต.คลัง อ.เมือง จ.นครศรีธรรมราช,ศูนย์ฟื้นฟูสุขภาพผู้สูงอายุ,Nakhon Si Thammarat
95,93T,ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง,วิทยาลัยสารพัดช่างตรัง,Trang

In [28]:
dfs_pm = {}

for i in range(2011, 2025):
    dfs_pm[i] = pd.read_excel(f"../../data/pm2-5/Raw_Data/PM2.5/PM2.5({i}).xlsx", sheet_name="PM2.5")

In [ ]:
# dfs_pm[2024]

,Date,02T,05T,10T,11T,12T,59T,61T,03T,50T,...,98T,42T,43T,44T,62T,63T,78T,80T,89T,93T
0,2024-01-01 00:00:00,38.3,29.4,28.2,29.0,24.3,22.0,23.3,34.3,31.4,...,31.6,19.8,23.6,17.0,19.0,19.0,10.6,18.9,22.4,11.6
1,2024-01-02 00:00:00,39.5,29.0,25.8,26.6,27.4,21.4,23.5,36.9,33.1,...,29.9,9.2,19.9,13.3,15.7,18.4,10.2,16.5,14.5,11.5
2,2024-01-03 00:00:00,38.2,28.7,26.3,23.7,25.8,21.4,23.5,35.9,30.3,...,37.2,13.2,22.6,15.5,18.9,19.1,9.2,18.4,14.0,11.3
3,2024-01-04 00:00:00,36.6,36.4,31.1,28.9,29.1,22.9,25.8,37.8,32.1,...,32.4,15.9,22.6,17.2,21.5,21.0,10.2,21.8,18.7,13.1
4,2024-01-05 00:00:00,36.0,32.6,30.1,26.5,25.5,20.6,25.4,35.8,32.5,...,34.1,NaN,23.7,17.7,23.6,22.2,11.7,24.0,20.0,24.9
5,2024-01-06 00:00:00,42.8,37.3,33.9,31.5,32.2,25.9,30.1,39.8,35.9,...,40.7,NaN,31.7,20.7,20.5,25.2,13.6,30.1,25.0,25.1
6,2024-01-07 00:00:00,44.0,38.6,34.8,33.0,32.8,25.1,31.0,41.7,35.4,...,43.7,22.1,35.7,16.7,18.3,19.0,9.6,18.2,24.0,18.3
7,2024-01-08 00:00:00,49.3,40.3,39.6,35.9,37.3,28.9,32.9,48.5,42.3,...,48.4,24.0,26.7,14.8,20.8,20.0,10.6,15.9,20.6,17.2
8,2024-01-09 00:00:00,68.0,58.7,57.4,49.0,56.3,39.9,45.5,75.5,61.1,...,59.1,17.4,25.9,14.6,20.0,20.6,10.7,17.4,23.3,17.4
9,2024-01-10 00:00:00,44.3,40.4,48.7,37.8,41.3,29.6,36.0,44.7,42.3,...,69.6,28.8,32.9,14.5,19.0,19.9,9.4,15.2,16.1,14.2
10,2024-01-11 00:00:00,36.7,32.1,36.0,31.4,35.1,24.1,29.5,35.5,35.0,...,65.6,22.4,26.6,15.2,20.2,23.4,10.8,18.9,18.9,15.7
11,2024-01-12 00:00:00,31.0,26.7,26.1,27.8,26.1,20.4,26.2,31.3,29.1,...,56.2,23.2,26.1,19.2,22.1,22.7,9.4,23.2,18.0,18.6
12,2024-01-13 00:00:00,34.8,29.2,28.3,27.2,28.8,21.2,25.9,32.3,31.3,...,53.0,25.6,30.0,20.8,23.9,24.9,11.4,26.9,20.1,21.5
13,2024-01-14 00:00:00,40.4,39.2,34.5,31.8,35.2,27.2,31.1,35.6,35.2,...,41.4,22.6,31.7,23.6,20.4,22.4,10.8,25.8,21.0,23.1
14,2024-01-15 00:00:00,37.6,33.6,27.3,31.1,29.1,22.0,27.2,36.2,32.0,...,31.2,24.2,32.0,16.5,20.2,19.8,9.9,17.5,25.6,21.5
15,2024-01-16 00:00:00,39.2,35.8,33.6,30.9,30.5,22.8,27.7,36.7,33.0,...,28.6,28.3,27.2,19.0,20.1,22.2,9.9,22.3,16.5,14.3
16,2024-01-17 00:00:00,47.7,45.2,36.2,37.0,39.9,28.8,34.4,47.4,42.7,...,36.6,23.5,26.2,16.4,20.5,19.3,11.9,18.7,18.1,23.2
17,2024-01-18 00:00:00,58.9,47.7,41.5,41.9,43.5,33.1,38.9,60.0,47.8,...,44.6,22.9,30.7,15.4,22.5,23.1,9.4,18.8,18.4,21.6
18,2024-01-19 00:00:00,70.3,59.0,48.5,48.9,60.0,40.5,45.8,73.7,63.1,...,56.3,20.3,23.9,17.5,21.3,20.7,11.5,27.2,11.1,21.6
19,2024-01-20 00:00:00,49.6,50.5,50.3,44.7,48.2,33.0,41.9,49.7,47.2,...,57.1,27.8,29.3,22.5,25.0,25.2,13.0,30.1,16.4,21.2
20,2024-01-21 00:00:00,40.0,37.2,35.8,33.1,35.2,27.4,31.7,44.5,36.9,...,48.4,25.9,38.2,26.4,25.6,26.5,15.4,32.0,17.4,20.7
21,2024-01-22 00:00:00,43.4,42.0,38.2,37.9,38.1,30.1,35.2,46.2,43.1,...,38.8,24.8,31.4,17.2,15.0,17.2,12.5,23.1,15.7,18.7
22,2024-01-23 00:00:00,55.4,49.6,50.4,45.4,46.0,38.0,40.3,54.8,49.1,...,46.6,13.5,21.4,11.8,11.2,14.0,8.2,11.6,11.6,8.0
23,2024-01-24 00:00:00,35.7,33.9,24.7,28.4,28.4,19.1,26.9,35.3,32.4,...,29.3,16.0,24.5,14.1,13.7,12.8,9.5,16.8,18.9,11.7
24,2024-01-25 00:00:00,31.7,31.0,24.1,24.1,24.0,20.4,21.8,30.1,32.4,...,40.4,9.3,20.1,13.1,16.5,15.8,8.3,14.5,15.2,12.0
25,2024-01-26 00:00:00,39.8,37.5,32.7,30.4,32.8,24.8,29.4,37.1,38.6,...,43.1,12.3,22.2,15.9,19.2,19.0,9.5,16.2,21.0,18.4
26,2024-01-27 00:00:00,48.5,47.1,45.0,38.9,42.2,33.2,37.0,45.7,46.7,...,48.4,17.8,24.4,16.7,20.6,20.9,10.7,18.2,24.0,23.1
27,2024-01-28 00:00:00,52.8,57.4,50.3,46.8,48.9,36.6,42.4,56.1,52.7,...,53.5,17.7,24.0,17.2,20.9,20.7,10.5,17.7,20.9,20.7
28,2024-01-29 00:00:00,44.3,42.6,37.1,38.0,38.3,30.8,35.7,46.3,42.4,...,40.8,17.2,23.9,17.1,21.6,21.9,11.6,20.8,18.9,22.4
29,2024-01-30 00:00:00,73.5,59.2,61.1,56.0,59.0,49.3,51.9,67.5,67.4,...,56.7,17.1,22.8,16.1,20.7,20.4,11.4,19.4,26.1,19.5
30,2024-01-31 00:00:00,61.3,64.1,64.0,53.2,57.0,44.3,51.1,62.1,61.5,...,43.1,20.4,27.0,16.9,21.9,22.3,11.1,21.0,19.5,16.3
31,2024-02-01 00:00:00,35.9,34.0,37.0,31.0,31.5,24.4,28.8,38.5,34.6,...,57.1,20.8,29.7,19.6,21.7,21.8,10.4,25.8,20.8,14.7
32,2024-02-02 00:00:00,27.8,24.0,23.8,24.3,24.1,19.4,23.8,30.5,27.5,...,51.9,22.3,31.5,21.3,21.7,21.6,10.8,23.7,19.6,NaN
33,2024-02-03 00:00:00,29.1,26.8,24.0,24.0,NaN,19.4,22.4,32.4,28.3,...,49.2,22.9,29.0,17.4,18.8,20.5,9.7,21.0,17.5,15.0
34,2024-02-04 00:00:00,30.5,28.2,26.0,24.0,22.7,21.3,22.7,31.4,29.5,...,43.0,26.0,35.3,19.8,22.1,22.9,13.3,23.7,20.9,14.6
35,2024-02-05 00:00:00,37.6,30.9,31.5,31.6,29.4,26.5,28.9,40.2,35.5,...,55.3,34.0,36.5,25.8,NaN,28.6,15.3,37.8,30.3,19.8
36,2024-02-06 00:00:00,31.4,26.5,24.9,25.9,26.2,22.7,25.5,36.9,30.4,...,63.4,31.0,36.6,20.3,22.3,23.6,12.5,24.8,26.1,21.1
37,2024-02-07 00:00:00,28.5,26.0,25.1,24.2,25.1,19.3,23.5,33.2,28.4,...,63.7,28.7,37.9,20.7,22.9,23.3,12.3,22.2,19.7,19.4
38,2024-02-08 00:00:00,27.7,24.0,21.9,23.8,23.4,18.6,22.4,32.9,26.8,...,83.8,28.5,36.6,21.0,23.6,23.2,12.7,24.0,19.1,16.5
39,2024-02-09 00:00:00,25.8,23.1,20.8,22.2,22.9,17.1,20.2,27.1,25.9,...,55.5,29.0,32.2,23.2,25.4,25.3,17.4,31.8,19.3,18.3
40,2024-02-10 00:00:00,41.6,38.0,36.3,33.7,35.3,28.5,30.9,38.4,40.0,...,43.7,21.1,28.7,19.9,23.8,24.5,17.5,22.7,18.3,15.6
41,2024-02-11 00:00:00,43.9,40.5,35.2,35.4,34.3,28.6,33.4,42.1,40.8,...,46.4,21.4,28.5,20.0,23.7,23.4,20.6,26.8,16.3,14.0
42,2024-02-12 00:00:00,59.2,56.8,55.5,52.5,49.6,45.2,47.8,56.1,55.5,...,62.6,21.7,31.0,21.5,23.6,23.4,18.9,26.8,28.5,18.6
43,2024-02-13 00:00:00,66.5,68.1,71.0,59.3,56.1,50.3,55.6,65.1,60.5,...,54.8,21.2,27.5,19.8,23.1,23.2,19.2,23.6,21.5,16.9
44,2024-02-14 00:00:00,79.0,77.5,76.6,69.3,73.4,53.3,65.6,79.0,74.1,...,63.4,18.0,28.8,18.4,22.0,21.6,16.5,23.1,27.8,15.6
45,2024-02-15 00:00:00,60.5,51.6,57.1,53.6,52.1,42.7,51.0,59.4,55.1,...,62.8,18.7,24.8,17.4,22.0,22.1,20.8,23.0,15.0,12.2
46,2024-02-16 00:00:00,33.2,28.7,30.2,30.5,29.7,24.2,27.0,33.9,33.7,...,74.1,20.5,28.5,16.8,22.5,22.6,19.2,21.5,18.7,16.0
47,2024-02-17 00:00:00,28.5,28.1,23.3,25.7,22.5,19.0,21.6,28.7,27.1,...,55.5,19.4,28.3,18.7,19.9,20.8,15.3,22.3,21.5,12.9
48,2024-02-18 00:00:00,24.2,20.5,17.7,18.8,18.2,15.1,18.2,24.8,21.4,...,40.2,20.4,29.9,18.9,20.5,20.4,14.1,23.7,21.9,14.3
49,2024-02-19 00:00:00,21.0,18.6,14.7,17.5,16.5,14.0,16.5,22.6,19.5,...,32.8,18.5,25.7,14.8,18.5,19.4,13.3,21.5,16.2,10.8
50,2024-02-20 00:00:00,18.8,16.6,12.7,15.1,13.1,10.9,16.3,20.3,18.4,...,31.9,16.5,22.5,16.2,17.9,18.1,12.1,18.7,13.6,12.7
51,2024-02-21 00:00:00,20.2,18.4,13.1,15.7,15.0,12.8,16.7,20.5,19.9,...,27.8,13.9,24.8,15.8,15.6,16.7,12.9,18.6,10.3,9.0
52,2024-02-22 00:00:00,19.8,17.0,13.6,15.8,15.4,12.6,16.3,20.4,19.3,...,29.9,12.7,24.5,13.7,17.6,18.2,19.2,17.8,10.7,8.8
53,2024-02-23 00:00:00,20.0,16.6,13.7,16.0,16.1,12.3,17.1,21.1,20.2,...,36.9,14.7,24.2,12.6,15.4,17.9,16.4,12.2,9.3,9.8
54,2024-02-24 00:00:00,22.2,17.9,16.0,17.7,16.5,15.0,17.7,22.1,21.6,...,38.9,13.0,18.3,11.8,13.9,15.0,12.3,11.2,13.8,9.8
55,2024-02-25 00:00:00,19.5,18.9,17.1,19.0,16.9,14.9,18.8,20.6,21.8,...,43.8,14.5,23.8,15.8,18.4,18.0,17.2,15.6,14.5,12.0
56,2024-02-26 00:00:00,31.5,27.6,27.6,26.4,25.7,21.9,22.4,28.8,31.7,...,45.5,21.5,28.5,19.0,20.8,20.7,20.5,25.6,19.6,15.6
57,2024-02-27 00:00:00,38.8,34.3,36.4,34.1,33.8,28.3,29.9,37.6,40.0,...,57.8,17.9,25.1,16.4,20.4,20.1,19.7,20.6,20.0,11.6
58,2024-02-28 00:00:00,28.0,26.2,22.0,24.0,22.6,17.4,21.5,26.4,27.6,...,58.4,16.2,22.3,18.6,20.4,20.1,17.8,23.8,22.9,11.2
59,2024-02-29 00:00:00,22.5,21.4,17.9,18.4,17.9,16.4,18.5,22.9,23.3,...,41.8,21.1,26.8,18.8,20.8,20.6,20.2,22.1,20.8,12.9
60,2024-03-01 00:00:00,25.8,24.3,21.1,21.3,20.7,16.8,20.5,23.3,26.4,...,NaN,19.0,27.0,19.6,20.0,19.9,17.6,26.4,18.5,15.7
61,2024-03-02 00:00:00,29.0,27.9,25.1,25.7,23.8,20.3,21.9,27.9,29.0,...,NaN,22.0,29.2,19.9,20.1,20.1,16.0,24.0,19.7,14.1
62,2024-03-03 00:00:00,29.2,29.4,24.3,27.0,24.6,20.4,22.8,27.3,28.9,...,57.6,19.2,29.5,18.0,20.2,20.0,13.1,22.7,21.8,12.0
63,2024-03-04 00:00:00,28.2,24.6,23.2,24.9,22.5,20.1,20.9,27.1,27.4,...,45.4,21.0,30.0,19.0,20.7,21.1,15.5,26.7,20.4,13.6
64,2024-03-05 00:00:00,27.6,25.7,20.9,21.7,21.2,19.2,20.7,26.4,26.8,...,43.3,22.0,29.9,22.5,20.5,20.6,15.9,28.9,17.6,16.5
65,2024-03-06 00:00:00,25.1,23.7,19.6,20.7,20.1,16.2,19.1,23.6,25.6,...,51.1,27.4,31.7,24.7,19.4,19.8,16.5,26.0,21.5,23.1
66,2024-03-07 00:00:00,31.3,28.7,24.0,26.4,25.5,21.6,22.2,29.5,31.4,...,62.9,26.3,41.8,22.6,19.7,18.8,13.3,33.4,22.3,23.2
67,2024-03-08 00:00:00,27.1,25.2,20.9,23.1,21.9,18.0,20.6,26.3,27.1,...,51.2,25.7,45.3,22.7,18.6,19.8,15.6,35.3,15.6,23.4
68,2024-03-09 00:00:00,25.7,23.3,19.9,21.8,20.1,18.8,19.3,23.1,25.1,...,38.0,26.9,28.6,17.5,19.4,19.3,15.3,14.3,21.2,14.4
69,2024-03-10 00:00:00,21.5,20.6,17.4,17.5,17.3,14.0,18.4,20.6,22.0,...,40.8,NaN,33.6,23.0,22.5,22.7,16.9,31.2,23.3,17.4
70,2024-03-11 00:00:00,38.2,34.9,32.8,34.5,32.7,29.3,27.2,37.8,37.2,...,43.8,NaN,37.3,24.2,24.9,24.8,19.1,29.4,25.7,21.2
71,2024-03-12 00:00:00,33.0,30.6,26.2,29.5,25.8,23.5,25.6,31.0,31.8,...,53.5,23.8,33.5,24.1,21.6,21.8,18.6,22.1,18.0,16.7
72,2024-03-13 00:00:00,27.7,25.2,20.7,22.7,21.5,18.9,20.2,27.1,26.9,...,53.0,22.1,31.7,21.4,20.7,20.7,19.7,20.3,15.9,16.6
73,2024-03-14 00:00:00,27.4,24.1,19.7,21.2,19.3,17.8,19.6,24.8,26.6,...,43.0,25.3,26.6,19.7,19.3,19.5,19.1,17.7,16.6,15.5
74,2024-03-15 00:00:00,24.1,23.0,18.4,19.9,17.3,16.3,19.0,23.9,25.0,...,61.3,20.2,25.1,21.7,21.7,22.0,20.7,23.9,17.8,16.7
75,2024-03-16 00:00:00,24.7,23.3,18.7,20.1,18.8,16.1,18.9,24.3,23.0,...,44.8,24.1,26.7,16.4,19.3,19.3,16.2,18.8,17.6,15.0
76,2024-03-17 00:00:00,26.3,22.5,18.4,20.9,18.8,16.3,18.8,24.4,24.6,...,53.0,22.5,21.3,19.8,18.9,19.1,16.5,17.1,16.6,13.7
77,2024-03-18 00:00:00,29.5,28.2,25.5,24.3,23.7,20.2,22.7,28.7,29.8,...,59.9,24.9,22.5,18.4,19.3,19.4,15.7,15.2,18.7,12.9
78,2024-03-19 00:00:00,31.5,30.8,26.5,27.1,26.6,24.3,25.2,29.5,32.9,...,52.0,19.7,20.3,17.4,19.5,19.6,15.4,16.7,16.5,12.8
79,2024-03-20 00:00:00,37.1,41.1,34.4,28.1,30.7,27.8,27.8,31.8,38.2,...,25.2,25.1,24.9,19.2,21.0,20.9,16.4,17.8,21.4,16.8
80,2024-03-21 00:00:00,53.3,53.1,50.2,42.7,43.3,33.5,37.7,51.3,52.4,...,37.3,23.3,23.2,20.2,21.2,21.2,17.8,20.6,22.6,15.9
81,2024-03-22 00:00:00,51.4,46.2,40.3,41.2,40.7,39.2,39.2,52.2,49.9,...,53.5,22.8,27.5,22.5,22.1,22.2,18.7,19.4,19.3,15.6
82,2024-03-23 00:00:00,23.7,25.0,17.1,17.2,18.8,15.7,18.7,24.4,25.5,...,34.7,19.2,23.7,22.2,21.2,20.8,17.5,19.1,19.0,17.3
83,2024-03-24 00:00:00,24.4,25.5,19.6,22.1,18.8,18.9,19.2,24.5,23.9,...,32.2,21.4,27.1,18.9,18.8,18.8,16.7,22.0,16.7,17.3
84,2024-03-25 00:00:00,24.0,25.9,20.0,23.8,20.8,20.2,20.1,25.5,26.9,...,41.3,21.3,23.4,14.9,15.3,16.6,14.8,16.5,13.4,15.6
85,2024-03-26 00:00:00,21.1,22.5,17.0,20.2,18.0,16.7,18.1,22.4,22.2,...,42.4,16.7,19.2,20.4,16.7,17.9,14.6,14.8,18.7,11.7
86,2024-03-27 00:00:00,19.6,23.3,18.2,19.3,18.2,15.5,17.4,20.6,23.2,...,45.4,17.3,19.7,12.8,16.3,16.7,15.2,12.8,14.6,11.0
87,2024-03-28 00:00:00,21.5,23.4,17.1,17.8,17.9,14.8,18.1,23.5,23.0,...,44.1,16.9,21.0,18.5,15.6,16.3,14.4,14.1,15.6,13.6
88,2024-03-29 00:00:00,24.6,27.5,21.0,26.4,22.0,21.6,20.6,26.3,28.0,...,45.0,18.1,19.5,15.4,15.8,17.1,13.3,13.0,19.0,14.5
89,2024-03-30 00:00:00,17.3,20.0,13.2,20.3,15.2,13.6,16.9,21.0,21.5,...,40.5,19.7,16.7,17.5,16.1,15.8,13.3,12.0,16.1,12.1
90,2024-03-31 00:00:00,17.7,18.8,13.3,18.5,14.2,12.6,16.3,18.1,19.6,...,40.1,19.4,21.6,20.6,14.3,15.0,11.7,16.4,10.2,19.0
91,2024-04-01 00:00:00,31.1,27.9,26.3,31.4,25.4,25.4,23.9,30.0,34.4,...,54.8,13.5,17.6,21.3,13.7,14.0,11.2,17.9,13.0,13.8
92,2024-04-02 00:00:00,28.1,27.3,21.7,30.0,23.5,23.6,23.2,27.9,30.0,...,79.0,17.9,26.7,23.0,16.1,15.7,11.2,16.2,12.4,11.3
93,2024-04-03 00:00:00,28.0,27.9,21.9,29.1,24.3,24.0,23.3,28.1,30.4,...,65.2,22.7,33.2,16.4,NaN,17.3,13.7,22.3,14.0,11.2
94,2024-04-04 00:00:00,24.6,25.7,20.9,27.9,19.9,22.0,20.4,24.2,27.5,...,62.6,23.8,28.4,19.8,18.4,18.8,14.6,28.8,14.1,19.5
95,2024-04-05 00:00:00,25.4,28.3,23.0,29.5,22.7,22.9,21.6,26.4,30.0,...,57.9,29.0,26.4,25.4,19.3,NaN,16.9,32.5,16.4,19.8
96,2024-04-06 00:00:00,25.0,28.3,22.7,29.1,21.9,23.4,22.8,25.5,28.4,...,60.4,21.9,26.9,25.8,19.3,NaN,16.8,35.0,18.8,19.4
97,2024-04-07 00:00:00,21.2,23.4,18.5,24.2,18.6,18.8,18.1,22.2,24.9,...,49.1,22.2,31.0,19.5,14.8,17.6,16.8,25.7,16.9,17.1
98,2024-04-08 00:00:00,20.3,21.6,15.7,20.5,18.1,17.2,18.0,20.6,22.7,...,54.2,20.3,25.2,20.5,12.1,15.8,NaN,22.2,10.7,12.5
99,2024-04-09 00:00:00,14.3,16.4,12.4,15.8,13.8,11.3,15.1,14.9,19.0,...,38.9,16.3,21.6,17.2,12.5,13.9,11.6,19.1,10.4,9.1
100,2024-04-10 00:00:00,22.8,22.6,19.6,20.2,17.2,18.7,18.5,21.1,24.4,...,50.4,14.4,17.0,15.8,12.9,14.2,11.4,16.1,12.2,10.3
101,2024-04-11 00:00:00,56.8,50.3,50.9,51.2,46.3,47.2,43.5,52.4,57.8,...,63.1,20.1,23.7,18.6,16.1,16.2,13.7,24.3,16.2,12.2
102,2024-04-12 00:00:00,29.1,32.3,28.0,29.0,25.8,24.8,25.8,28.4,31.6,...,64.3,17.8,20.6,18.3,16.7,17.7,15.9,23.8,16.8,15.2
103,2024-04-13 00:00:00,26.7,29.9,25.1,25.5,23.0,23.6,23.1,26.1,29.1,...,52.8,21.0,26.1,22.7,20.5,20.1,16.3,23.1,17.9,16.7
104,2024-04-14 00:00:00,28.5,29.0,23.9,25.7,22.7,23.6,23.3,26.9,29.4,...,48.4,23.0,28.7,24.4,19.6,20.1,17.3,31.3,18.9,16.8
105,2024-04-15 00:00:00,27.5,27.2,22.9,24.8,21.5,21.4,21.7,23.3,27.5,...,39.7,21.9,23.2,17.7,13.6,14.4,12.7,27.9,17.0,16.2
106,2024-04-16 00:00:00,21.8,23.6,19.9,20.1,18.4,18.2,19.1,21.5,24.7,...,36.5,16.4,22.0,15.8,13.3,14.2,12.4,20.4,10.6,11.4
107,2024-04-17 00:00:00,22.6,22.9,18.1,20.5,18.6,17.9,18.9,21.3,24.0,...,37.7,15.7,22.0,13.7,13.7,14.0,12.1,16.2,11.2,12.6
108,2024-04-18 00:00:00,25.4,26.0,20.4,23.2,20.8,20.4,20.7,24.2,27.6,...,43.2,15.5,23.9,20.7,12.3,13.2,10.6,17.4,10.8,14.1
109,2024-04-19 00:00:00,33.5,33.3,27.7,34.0,27.7,27.6,26.4,33.3,35.8,...,49.5,20.4,26.9,24.2,13.3,14.3,12.7,16.6,17.1,20.0
110,2024-04-20 00:00:00,42.2,41.0,37.9,41.1,35.1,36.5,34.9,41.5,44.0,...,55.4,23.1,22.1,23.2,15.2,16.3,15.0,20.7,14.5,19.1
111,2024-04-21 00:00:00,46.7,47.6,39.8,42.6,39.6,38.4,38.1,44.1,47.0,...,60.1,18.5,23.8,19.3,14.6,16.2,14.4,19.2,14.5,13.2
112,2024-04-22 00:00:00,34.7,32.2,28.4,33.9,28.8,32.3,29.1,31.7,35.3,...,56.9,23.8,25.3,25.8,17.4,16.5,13.8,21.9,19.9,17.1
113,2024-04-23 00:00:00,29.6,29.4,24.1,28.7,24.9,24.1,21.9,29.4,31.1,...,47.5,22.3,27.9,22.1,17.0,17.4,13.9,23.3,17.9,18.1
114,2024-04-24 00:00:00,20.6,21.3,15.7,18.1,16.8,15.9,16.7,20.5,22.8,...,37.4,20.1,29.9,25.5,17.3,17.4,13.3,24.9,15.5,15.9
115,2024-04-25 00:00:00,14.6,15.8,11.4,14.4,11.7,10.3,14.2,15.7,17.7,...,34.7,16.9,29.3,23.1,16.7,18.0,15.7,27.9,15.1,17.2
116,2024-04-26 00:00:00,18.0,19.1,12.9,15.1,12.6,14.3,15.8,17.5,19.8,...,30.1,19.2,21.7,21.7,15.8,15.7,14.7,18.6,14.0,16.7
117,2024-04-27 00:00:00,20.2,22.1,17.9,20.6,16.2,14.5,18.1,21.6,22.9,...,32.4,18.1,26.0,17.1,15.2,16.3,14.7,20.8,13.4,19.0
118,2024-04-28 00:00:00,15.4,15.7,10.1,12.2,11.4,11.3,14.8,17.7,17.3,...,35.9,16.8,26.0,19.8,15.9,16.2,15.5,17.2,11.1,13.7
119,2024-04-29 00:00:00,13.4,15.3,10.0,14.5,11.3,10.7,14.3,16.6,17.7,...,32.1,15.0,21.0,16.8,14.5,15.5,12.9,15.7,10.5,15.5
120,2024-04-30 00:00:00,32.0,29.0,24.9,33.4,25.8,28.0,24.7,34.8,33.5,...,44.1,15.3,25.3,19.2,16.1,16.3,13.6,20.0,10.3,13.3
121,2024-05-01 00:00:00,43.3,41.1,38.1,46.4,35.6,38.9,33.1,45.6,42.9,...,51.6,22.0,34.0,20.3,16.8,17.5,13.0,21.2,16.4,16.2
122,2024-05-02 00:00:00,39.7,39.0,34.6,42.4,32.0,35.1,32.7,42.2,40.2,...,51.6,20.7,39.7,19.0,19.8,18.3,15.0,16.6,18.8,17.3
123,2024-05-03 00:00:00,35.1,34.1,27.4,38.4,28.3,29.6,24.6,38.5,35.7,...,42.2,25.9,37.0,22.1,20.1,19.5,17.6,18.6,16.1,20.6
124,2024-05-04 00:00:00,32.1,33.0,28.7,34.7,25.4,27.9,24.8,36.7,34.0,...,40.5,23.8,34.1,22.3,15.6,15.3,13.5,19.6,19.5,20.5
125,2024-05-05 00:00:00,40.7,39.5,37.7,44.0,32.2,33.5,33.7,42.8,41.9,...,42.8,23.5,37.8,20.6,17.9,17.3,15.2,20.8,20.7,18.9
126,2024-05-06 00:00:00,37.6,37.3,32.2,39.4,30.7,32.8,31.5,41.3,38.5,...,48.0,20.7,NaN,22.0,16.9,17.1,15.4,20.5,18.8,18.5
127,2024-05-07 00:00:00,23.4,24.9,17.0,21.7,17.9,16.4,18.3,26.0,25.4,...,36.5,16.8,19.6,18.9,15.5,15.2,13.9,18.2,15.9,15.6
128,2024-05-08 00:00:00,21.7,27.1,21.0,25.2,18.8,14.3,20.3,27.1,25.7,...,33.0,14.7,16.1,14.3,17.3,16.6,14.8,16.1,9.9,14.7
129,2024-05-09 00:00:00,18.8,19.4,21.3,22.4,17.6,14.8,19.8,23.3,23.8,...,33.4,13.3,16.8,14.1,18.1,18.4,17.4,15.7,10.6,11.8
130,2024-05-10 00:00:00,17.5,20.1,13.5,20.2,15.0,14.0,16.3,20.9,19.0,...,23.8,12.9,13.4,13.8,NaN,14.1,NaN,15.4,11.3,7.5
131,2024-05-11 00:00:00,19.6,22.2,18.9,16.4,15.4,14.8,17.8,20.4,22.6,...,21.5,12.4,16.1,15.3,16.1,15.6,NaN,12.0,6.1,10.4
132,2024-05-12 00:00:00,30.2,31.2,27.3,26.0,21.5,21.1,22.8,31.1,29.8,...,18.3,13.7,12.5,14.2,12.8,14.7,14.4,12.1,8.4,11.2
133,2024-05-13 00:00:00,20.6,20.5,15.0,15.9,13.0,14.0,16.8,22.4,21.8,...,24.9,12.7,15.7,17.8,14.9,15.1,14.2,15.5,9.7,16.8
134,2024-05-14 00:00:00,27.0,25.8,20.1,17.6,18.0,16.0,19.6,28.0,26.3,...,13.8,13.7,17.7,15.0,14.1,14.3,13.8,16.8,12.2,14.5
135,2024-05-15 00:00:00,40.6,32.3,30.6,29.7,26.9,27.9,27.2,39.4,37.7,...,22.1,13.2,13.8,15.0,14.8,14.9,14.6,15.3,8.5,11.6
136,2024-05-16 00:00:00,22.1,22.8,22.5,20.0,19.6,17.0,19.9,21.8,24.7,...,33.0,14.8,14.4,13.8,15.5,15.4,14.9,13.9,10.9,11.4
137,2024-05-17 00:00:00,17.5,14.7,12.4,15.0,13.4,10.7,15.7,18.2,18.4,...,29.9,12.3,13.4,13.7,11.7,11.8,11.5,11.1,9.4,9.1
138,2024-05-18 00:00:00,19.1,16.1,14.5,13.4,13.2,11.6,15.4,17.4,17.9,...,25.6,11.3,12.5,13.5,11.7,13.1,11.8,13.4,7.6,11.4
139,2024-05-19 00:00:00,18.8,14.7,11.4,13.1,10.2,10.7,13.5,15.6,16.6,...,18.9,12.7,14.7,14.0,12.6,13.9,13.0,14.1,8.2,14.6
140,2024-05-20 00:00:00,18.3,14.0,12.1,13.4,10.8,10.2,15.1,17.8,19.7,...,16.8,11.7,12.1,13.7,11.4,12.9,11.2,13.7,11.6,11.3
141,2024-05-21 00:00:00,17.6,14.3,11.1,11.3,10.1,10.1,13.5,16.2,16.6,...,15.0,10.3,12.6,12.3,11.7,13.0,12.0,11.9,8.2,8.6
142,2024-05-22 00:00:00,16.5,12.9,8.8,11.0,8.3,9.2,13.5,16.8,16.1,...,12.8,7.4,9.1,11.2,11.9,12.8,11.1,10.6,9.4,6.6
143,2024-05-23 00:00:00,15.4,11.2,8.8,8.6,7.7,7.4,13.2,15.9,15.3,...,11.2,8.5,12.1,12.0,12.2,12.0,10.8,11.0,13.3,8.8
144,2024-05-24 00:00:00,14.3,11.0,6.6,7.7,8.1,5.8,12.8,16.0,14.3,...,14.0,12.3,13.7,13.2,12.0,13.0,11.2,13.1,12.8,11.0
145,2024-05-25 00:00:00,13.2,11.3,8.0,9.6,7.5,6.2,12.9,14.4,14.3,...,13.6,14.2,15.3,14.1,13.2,13.4,11.4,14.1,11.8,14.2
146,2024-05-26 00:00:00,13.5,10.7,7.8,7.9,6.9,5.2,11.3,12.6,12.7,...,13.2,13.4,18.6,14.9,13.2,13.4,10.2,15.8,12.2,16.3
147,2024-05-27 00:00:00,15.2,11.9,9.9,11.5,8.1,7.1,13.6,15.5,16.6,...,12.7,14.9,17.3,17.6,15.5,15.9,13.7,17.5,13.3,10.1
148,2024-05-28 00:00:00,18.7,15.1,10.5,12.4,9.9,9.2,13.0,18.7,16.9,...,12.2,14.5,17.3,14.5,15.2,14.6,12.8,13.4,13.2,12.6
149,2024-05-29 00:00:00,20.8,15.4,10.2,15.8,10.5,11.1,14.0,18.9,18.8,...,11.2,14.0,13.7,14.5,12.4,13.5,11.9,14.3,14.0,14.1
150,2024-05-30 00:00:00,18.9,16.0,11.7,13.0,11.1,9.3,14.3,18.5,19.2,...,10.5,12.0,13.5,12.6,11.5,13.1,12.2,12.3,13.1,12.0
151,2024-05-31 00:00:00,14.9,13.7,8.3,9.2,8.7,6.6,12.4,14.1,16.3,...,11.3,8.8,11.5,11.2,11.4,13.2,11.8,11.4,8.4,8.1
152,2024-06-01 00:00:00,11.3,11.1,6.8,8.0,7.8,4.1,10.7,11.5,9.9,...,10.7,10.4,14.2,12.9,10.2,11.7,10.4,12.4,7.8,9.9
153,2024-06-02 00:00:00,12.8,10.0,6.5,7.7,6.2,5.8,10.0,13.5,9.7,...,10.3,11.2,13.7,11.9,9.4,10.5,9.0,11.7,8.8,9.3
154,2024-06-03 00:00:00,17.0,13.4,9.5,11.5,9.3,8.2,12.1,16.2,13.3,...,11.9,11.2,14.9,11.8,10.3,10.7,9.8,11.3,8.4,10.5
155,2024-06-04 00:00:00,19.8,18.5,13.5,14.7,13.4,12.4,14.8,20.1,17.0,...,13.9,11.5,13.8,12.8,11.6,11.7,10.5,12.4,12.9,10.7
156,2024-06-05 00:00:00,17.9,15.7,10.3,11.8,10.8,10.0,13.8,17.6,16.0,...,9.7,11.7,11.8,12.6,13.1,13.2,12.1,12.0,10.9,10.2
157,2024-06-06 00:00:00,15.2,14.1,9.3,9.2,10.3,7.4,13.0,14.5,15.0,...,9.7,11.9,11.6,12.1,11.5,11.7,10.6,12.2,13.1,11.8
158,2024-06-07 00:00:00,17.0,17.5,11.7,12.2,11.2,10.0,14.1,17.9,17.3,...,12.0,10.7,11.5,11.2,10.9,11.7,10.9,10.6,11.4,11.1
159,2024-06-08 00:00:00,21.2,16.4,11.7,14.4,12.7,10.8,14.4,20.2,18.4,...,16.0,12.4,11.8,12.3,10.5,11.2,10.2,11.8,10.0,10.5
160,2024-06-09 00:00:00,14.6,12.0,7.5,8.9,7.6,5.0,11.6,14.0,12.9,...,14.6,NaN,15.6,14.5,10.9,11.2,9.8,13.4,11.9,12.2
161,2024-06-10 00:00:00,11.7,9.8,6.5,5.8,6.2,5.0,9.9,12.3,12.2,...,11.0,12.2,14.9,13.0,12.3,12.4,11.0,13.3,10.0,13.6
162,2024-06-11 00:00:00,13.6,11.1,7.2,9.6,8.7,6.5,11.2,13.7,12.4,...,13.1,12.1,15.3,13.1,12.6,12.7,11.2,13.0,11.9,13.2

In [30]:
mapper = df_pmmap[['รหัสสถานี', 'ชื่อสถานี']]
mapper

   รหัสสถานี                                         ชื่อสถานี
0        02T                      แขวงหิรัญรูจี เขตธนบุรี กทม.
1        05T                           แขวงบางนา เขตบางนา กทม.
2        10T                      แขวงคลองจั่น เขตบางกะปิ กทม.
3        11T                         แขวงดินแดง เขตดินแดง กทม.
4        12T                     แขวงช่องนนทรี เขตยานนาวา กทม.
5        59T                           แขวงพญาไท เขตพญาไท กทม.
6        61T                    แขวงพลับพลา เขตวังทองหลาง กทม.
7        03T   ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.
8        50T       ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
9        52T  ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.
10       53T  ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.
11       54T            ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
12       08T               ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
13       16T                   ต.บางโปรง อ.เมือง จ.สมุทรปราการ
14       17T                  ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
15       18T                    ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
16       19T               ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
17       13T                      ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
18       22T                     ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
19       14T               ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
20       27T                      ต.มหาชัย อ.เมือง จ.สมุทรสาคร
21       20T                 ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
22       81T                         ต.นครปฐม อ.เมือง จ.นครปฐม
23       21T    ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา
24       24T         ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
25       25T                    ต.ปากเพรียว อ.เมือง จ.สระบุรี
26       26T                     ต.หน้าเมือง อ.เมือง จ.ราชบุรี
27       79T                   ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
28       84T                   ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
29       85T                   ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
30       99T                ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
31      103T               ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
32      104T                      ต.บางมัญ อ.เมือง จ.สิงห์บุรี
33       46T                       ต.ในเมือง อ.เมือง จ.ขอนแก่น
34       47T                    ต.ในเมือง อ.เมือง จ.นครราชสีมา
35       72T                           ต.กุดป่อง อ.เมือง จ.เลย
36       82T                         ต.มีชัย อ.เมือง จ.หนองคาย
37       83T                   ต.ในเมือง อ.เมือง จ.อุบลราชธานี
38       88T                        ต.ในเมือง อ.เมือง จ.นครพนม
39       90T                      ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
40       91T                     ต.หมากแข้ง อ.เมือง จ.อุดรธานี
41      101T                      ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
42      102T             ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
43      106T                         ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
44      107T                   ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
45      108T                       ต.ในเมือง อ.เมือง จ.ชัยภูมิ
46      109T                         ต.ในเมือง อ.เมือง จ.ยโสธร
47      110T                       ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
48      111T                     ต.นอกเมือง อ.เมือง จ.สุรินทร์
49      112T                      ต.หนองครก อ.เมือง จ.ศรีสะเกษ
50       28T                       ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
51       29T                        ต.มาบตาพุด อ.เมือง จ.ระยอง
52       30T                       ต.ท่าประดู่ อ.เมือง จ.ระยอง
53       31T                        ต.ห้วยโป่ง อ.เมือง จ.ระยอง
54       74T                         ต.เนินพระ อ.เมือง จ.ระยอง
55       32T                    ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
56       33T                       ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
57       34T                        ต.บ้านสวน อ.เมือง จ.ชลบุรี
58       60T                  ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
59       71T              ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
60       77T                ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
61       87T                           ต.บางพระ อ.เมือง จ.ตราด
62      100T              ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
63      105T                      ต.บ้านใหญ่ อ.เมือง จ.นครนายก
64       35T                   ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
65       36T                     ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
66       37T                          ต.พระบาท อ.เมือง จ.ลำปาง
67       38T                        ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
68       39T                        ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
69       40T                       ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
70       41T                    ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
71       57T                        ต.เวียง อ.เมือง จ.เชียงราย
72       73T                  ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
73       58T                      ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
74       67T                          ต.ในเวียง อ.เมือง จ.น่าน
75       75T               ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
76       68T                        ต.บ้านกลาง อ.เมือง จ.ลำพูน
77       69T                          ต.นาจักร อ.เมือง จ. แพร่
78       70T                   ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
79       76T                            ต.แม่ปะ อ.แม่สอด จ.ตาก
80       86T                      ต.ในเมือง อ.เมือง จ.พิษณุโลก
81       92T                      ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
82       94T            ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
83       95T                  ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
84       96T                          ต.ธานี อ.เมือง จ.สุโขทัย
85       97T            ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
86       98T          ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
87       42T               ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
88       43T                       ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
89       44T                       ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
90       62T                       ต.บางนาค อ.เมือง จ.นราธิวาส
91       63T                            ต.สะเตง อ.เมือง จ.ยะลา
92       78T                              ต.เบตง อ.เบตง จ.ยะลา
93       80T                           ต.พิมาน อ.เมือง. จ.สตูล
94       89T                    ต.คลัง อ.เมือง จ.นครศรีธรรมราช
95       93T                     ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง

In [31]:
# new_column = []

mapone = mapper["รหัสสถานี"]
maptwo = mapper["ชื่อสถานี"]
# columns_list = dfs_pm[2024].columns.tolist()

# for col in columns_list[1:]:
#     if col in mapone.values:
#         index = mapone[mapone == col].index[0]
#         new_column.append(f"{col} | {maptwo[index]}")
#     else:
#         new_column.append(col)

# # Update the columns of the DataFrame
# dfs_pm[2024].columns = [columns_list[0]] + new_column

#work only for each files

In [32]:
print(mapone)
print(maptwo)

0      02T
1      05T
2      10T
3      11T
4      12T
5      59T
6      61T
7      03T
8      50T
9      52T
10     53T
11     54T
12     08T
13     16T
14     17T
15     18T
16     19T
17     13T
18     22T
19     14T
20     27T
21     20T
22     81T
23     21T
24     24T
25     25T
26     26T
27     79T
28     84T
29     85T
30     99T
31    103T
32    104T
33     46T
34     47T
35     72T
36     82T
37     83T
38     88T
39     90T
40     91T
41    101T
42    102T
43    106T
44    107T
45    108T
46    109T
47    110T
48    111T
49    112T
50     28T
51     29T
52     30T
53     31T
54     74T
55     32T
56     33T
57     34T
58     60T
59     71T
60     77T
61     87T
62    100T
63    105T
64     35T
65     36T
66     37T
67     38T
68     39T
69     40T
70     41T
71     57T
72     73T
73     58T
74     67T
75     75T
76     68T
77     69T
78     70T
79     76T
80     86T
81     92T
82     94T
83     95T
84     96T
85     97T
86     98T
87     42T
88     43T
89     44T
90     62T
91     63T
92     78T
93     80T
94     89T
95     93T
Name: รหัสสถานี, dtype: object
0                         แขวงหิรัญรูจี เขตธนบุรี กทม.
1                              แขวงบางนา เขตบางนา กทม.
2                         แขวงคลองจั่น เขตบางกะปิ กทม.
3                            แขวงดินแดง เขตดินแดง กทม.
4                        แขวงช่องนนทรี เขตยานนาวา กทม.
5                              แขวงพญาไท เขตพญาไท กทม.
6                       แขวงพลับพลา เขตวังทองหลาง กทม.
7      ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.
8          ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
9     ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.
10    ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.
11              ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
12                 ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
13                     ต.บางโปรง อ.เมือง จ.สมุทรปราการ
14                    ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
15                      ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
16                 ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
17                        ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
18                       ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
19                 ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
20                        ต.มหาชัย อ.เมือง จ.สมุทรสาคร
21                   ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
22                           ต.นครปฐม อ.เมือง จ.นครปฐม
23      ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา
24           ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
25                      ต.ปากเพรียว อ.เมือง จ.สระบุรี
26                       ต.หน้าเมือง อ.เมือง จ.ราชบุรี
27                     ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
28                     ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
29                     ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
30                  ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
31                 ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
32                        ต.บางมัญ อ.เมือง จ.สิงห์บุรี
33                         ต.ในเมือง อ.เมือง จ.ขอนแก่น
34                      ต.ในเมือง อ.เมือง จ.นครราชสีมา
35                             ต.กุดป่อง อ.เมือง จ.เลย
36                           ต.มีชัย อ.เมือง จ.หนองคาย
37                     ต.ในเมือง อ.เมือง จ.อุบลราชธานี
38                          ต.ในเมือง อ.เมือง จ.นครพนม
39                        ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
40                       ต.หมากแข้ง อ.เมือง จ.อุดรธานี
41                        ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
42               ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
43                           ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
44                     ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
45                         ต.ในเมือง อ.เมือง จ.ชัยภูมิ
46                           ต.ในเมือง อ.เมือง จ.ยโสธร
47                         ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
48                       ต.นอกเมือง อ.เมือง จ.สุรินทร์
49                        ต.หนองครก อ.เมือง จ.ศรีสะเกษ
50                         ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
51                          ต.มาบตาพุด อ.เมือง จ.ระยอง
52                         ต.ท่าประดู่ อ.เมือง จ.ระยอง
53                          ต.ห้วยโป่ง อ.เมือง จ.ระยอง
54                           ต.เนินพระ อ.เมือง จ.ระยอง
55                      ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
56                         ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
57                          ต.บ้านสวน อ.เมือง จ.ชลบุรี
58                    ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
59                ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
60                  ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
61                             ต.บางพระ อ.เมือง จ.ตราด
62                ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
63                        ต.บ้านใหญ่ อ.เมือง จ.นครนายก
64                     ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
65                       ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
66                            ต.พระบาท อ.เมือง จ.ลำปาง
67                          ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
68                          ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
69                         ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
70                      ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
71                          ต.เวียง อ.เมือง จ.เชียงราย
72                    ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
73                        ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
74                            ต.ในเวียง อ.เมือง จ.น่าน
75                 ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
76                          ต.บ้านกลาง อ.เมือง จ.ลำพูน
77                            ต.นาจักร อ.เมือง จ. แพร่
78                     ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
79                              ต.แม่ปะ อ.แม่สอด จ.ตาก
80                        ต.ในเมือง อ.เมือง จ.พิษณุโลก
81                        ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
82              ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
83                    ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
84                            ต.ธานี อ.เมือง จ.สุโขทัย
85              ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
86            ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
87                 ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
88                         ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
89                         ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
90                         ต.บางนาค อ.เมือง จ.นราธิวาส
91                              ต.สะเตง อ.เมือง จ.ยะลา
92                                ต.เบตง อ.เบตง จ.ยะลา
93                             ต.พิมาน อ.เมือง. จ.สตูล
94                      ต.คลัง อ.เมือง จ.นครศรีธรรมราช
95                       ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง
Name: ชื่อสถานี, dtype: object

In [33]:
df_new_col = pd.DataFrame(new_column, columns=["Station Info"])
pd.set_option('display.max_rows', None)  # Ensure all rows are displayed
display(df_new_col)

                                         Station Info
0                  02T | แขวงหิรัญรูจี เขตธนบุรี กทม.
1                       05T | แขวงบางนา เขตบางนา กทม.
2                  10T | แขวงคลองจั่น เขตบางกะปิ กทม.
3                     11T | แขวงดินแดง เขตดินแดง กทม.
4                 12T | แขวงช่องนนทรี เขตยานนาวา กทม.
5                       59T | แขวงพญาไท เขตพญาไท กทม.
6                61T | แขวงพลับพลา เขตวังทองหลาง กทม.
7   03T | ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเที...
8   50T | ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
9   52T | ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบ...
10  53T | ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองห...
11       54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
12          08T | ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
13              16T | ต.บางโปรง อ.เมือง จ.สมุทรปราการ
14             17T | ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
15               18T | ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
16          19T | ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
17                 13T | ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
18                22T | ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
19          14T | ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
20                 27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร
21            20T | ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
22                    81T | ต.นครปฐม อ.เมือง จ.นครปฐม
23  21T | ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรี...
24    24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
25               25T | ต.ปากเพรียว อ.เมือง จ.สระบุรี
26                26T | ต.หน้าเมือง อ.เมือง จ.ราชบุรี
27              79T | ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
28              84T | ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
29              85T | ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
30           99T | ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
31         103T | ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
32                104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี
33                  46T | ต.ในเมือง อ.เมือง จ.ขอนแก่น
34               47T | ต.ในเมือง อ.เมือง จ.นครราชสีมา
35                      72T | ต.กุดป่อง อ.เมือง จ.เลย
36                    82T | ต.มีชัย อ.เมือง จ.หนองคาย
37              83T | ต.ในเมือง อ.เมือง จ.อุบลราชธานี
38                   88T | ต.ในเมือง อ.เมือง จ.นครพนม
39                 90T | ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
40                91T | ต.หมากแข้ง อ.เมือง จ.อุดรธานี
41                101T | ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
42       102T | ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
43                   106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
44             107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
45                 108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ
46                   109T | ต.ในเมือง อ.เมือง จ.ยโสธร
47                 110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
48               111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์
49                112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ
50                  28T | ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
51                   29T | ต.มาบตาพุด อ.เมือง จ.ระยอง
52                  30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง
53                   31T | ต.ห้วยโป่ง อ.เมือง จ.ระยอง
54                    74T | ต.เนินพระ อ.เมือง จ.ระยอง
55               32T | ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
56                  33T | ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
57                   34T | ต.บ้านสวน อ.เมือง จ.ชลบุรี
58             60T | ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
59         71T | ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
60           77T | ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
61                      87T | ต.บางพระ อ.เมือง จ.ตราด
62        100T | ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
63                105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก
64              35T | ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
65                36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
66                     37T | ต.พระบาท อ.เมือง จ.ลำปาง
67                   38T | ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
68                   39T | ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
69                  40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
70               41T | ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
71                   57T | ต.เวียง อ.เมือง จ.เชียงราย
72             73T | ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
73                 58T | ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
74                     67T | ต.ในเวียง อ.เมือง จ.น่าน
75          75T | ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
76                   68T | ต.บ้านกลาง อ.เมือง จ.ลำพูน
77                     69T | ต.นาจักร อ.เมือง จ. แพร่
78              70T | ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
79                       76T | ต.แม่ปะ อ.แม่สอด จ.ตาก
80                 86T | ต.ในเมือง อ.เมือง จ.พิษณุโลก
81                 92T | ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
82       94T | ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
83             95T | ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
84                     96T | ต.ธานี อ.เมือง จ.สุโขทัย
85       97T | ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
86     98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
87          42T | ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
88                  43T | ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
89                  44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
90                  62T | ต.บางนาค อ.เมือง จ.นราธิวาส
91                       63T | ต.สะเตง อ.เมือง จ.ยะลา
92                         78T | ต.เบตง อ.เบตง จ.ยะลา
93                      80T | ต.พิมาน อ.เมือง. จ.สตูล
94               89T | ต.คลัง อ.เมือง จ.นครศรีธรรมราช
95                93T | ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง

In [34]:
# dfs_pm[2024]

In [35]:
for i in range(2024, 2010, -1):
    mapper = df_pmmap.set_index('รหัสสถานี')['ชื่อสถานี'].to_dict()
    
    # Rename columns
    new_columns = []
    for col in dfs_pm[i].columns:
        print(f"Processing column: {col}")
        if col in mapper:
            new_columns.append(f"{col} | {mapper[col]}")
            print(f"Renamed {col} to {col} | {mapper[col]}")
        else:
            new_columns.append(col)
    
    dfs_pm[i].columns = new_columns
    
    # Remove last 2 rows
    dfs_pm[i] = dfs_pm[i].iloc[:-2]

Processing column: Date
Processing column: 02T
Renamed 02T to 02T | แขวงหิรัญรูจี เขตธนบุรี กทม.
Processing column: 05T
Renamed 05T to 05T | แขวงบางนา เขตบางนา กทม.
Processing column: 10T
Renamed 10T to 10T | แขวงคลองจั่น เขตบางกะปิ กทม.
Processing column: 11T
Renamed 11T to 11T | แขวงดินแดง เขตดินแดง กทม.
Processing column: 12T
Renamed 12T to 12T | แขวงช่องนนทรี เขตยานนาวา กทม.
Processing column: 59T
Renamed 59T to 59T | แขวงพญาไท เขตพญาไท กทม.
Processing column: 61T
Renamed 61T to 61T | แขวงพลับพลา เขตวังทองหลาง กทม.
Processing column: 03T
Renamed 03T to 03T | ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.
Processing column: 50T
Renamed 50T to 50T | ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
Processing column: 52T
Renamed 52T to 52T | ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.
Processing column: 53T
Renamed 53T to 53T | ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.
Processing column: 54T
Renamed 54T to 54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
Processing column: 08T
Renamed 08T to 08T | ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
Processing column: 16T
Renamed 16T to 16T | ต.บางโปรง อ.เมือง จ.สมุทรปราการ
Processing column: 17T
Renamed 17T to 17T | ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
Processing column: 18T
Renamed 18T to 18T | ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
Processing column: 19T
Renamed 19T to 19T | ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
Processing column: 13T
Renamed 13T to 13T | ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
Processing column: 22T
Renamed 22T to 22T | ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
Processing column: 14T
Renamed 14T to 14T | ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
Processing column: 27T
Renamed 27T to 27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร
Processing column: 20T
Renamed 20T to 20T | ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
Processing column: 81T
Renamed 81T to 81T | ต.นครปฐม อ.เมือง จ.นครปฐม
Processing column: 21T
Renamed 21T to 21T | ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา
Processing column: 24T
Renamed 24T to 24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
Processing column: 25T
Renamed 25T to 25T | ต.ปากเพรียว อ.เมือง จ.สระบุรี
Processing column: 26T
Renamed 26T to 26T | ต.หน้าเมือง อ.เมือง จ.ราชบุรี
Processing column: 79T
Renamed 79T to 79T | ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
Processing column: 84T
Renamed 84T to 84T | ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
Processing column: 85T
Renamed 85T to 85T | ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
Processing column: 99T
Renamed 99T to 99T | ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
Processing column: 103T
Renamed 103T to 103T | ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
Processing column: 104T
Renamed 104T to 104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี
Processing column: 46T
Renamed 46T to 46T | ต.ในเมือง อ.เมือง จ.ขอนแก่น
Processing column: 47T
Renamed 47T to 47T | ต.ในเมือง อ.เมือง จ.นครราชสีมา
Processing column: 72T
Renamed 72T to 72T | ต.กุดป่อง อ.เมือง จ.เลย
Processing column: 82T
Renamed 82T to 82T | ต.มีชัย อ.เมือง จ.หนองคาย
Processing column: 83T
Renamed 83T to 83T | ต.ในเมือง อ.เมือง จ.อุบลราชธานี
Processing column: 88T
Renamed 88T to 88T | ต.ในเมือง อ.เมือง จ.นครพนม
Processing column: 90T
Renamed 90T to 90T | ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
Processing column: 91T
Renamed 91T to 91T | ต.หมากแข้ง อ.เมือง จ.อุดรธานี
Processing column: 101T
Renamed 101T to 101T | ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
Processing column: 102T
Renamed 102T to 102T | ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
Processing column: 106T
Renamed 106T to 106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
Processing column: 107T
Renamed 107T to 107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
Processing column: 108T
Renamed 108T to 108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ
Processing column: 109T
Renamed 109T to 109T | ต.ในเมือง อ.เมือง จ.ยโสธร
Processing column: 110T
Renamed 110T to 110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
Processing column: 111T
Renamed 111T to 111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์
Processing column: 112T
Renamed 112T to 112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ
Processing column: 28T
Renamed 28T to 28T | ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
Processing column: 29T
Renamed 29T to 29T | ต.มาบตาพุด อ.เมือง จ.ระยอง
Processing column: 30T
Renamed 30T to 30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง
Processing column: 31T
Renamed 31T to 31T | ต.ห้วยโป่ง อ.เมือง จ.ระยอง
Processing column: 74T
Renamed 74T to 74T | ต.เนินพระ อ.เมือง จ.ระยอง
Processing column: 32T
Renamed 32T to 32T | ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
Processing column: 33T
Renamed 33T to 33T | ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
Processing column: 34T
Renamed 34T to 34T | ต.บ้านสวน อ.เมือง จ.ชลบุรี
Processing column: 60T
Renamed 60T to 60T | ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
Processing column: 71T
Renamed 71T to 71T | ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
Processing column: 77T
Renamed 77T to 77T | ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
Processing column: 87T
Renamed 87T to 87T | ต.บางพระ อ.เมือง จ.ตราด
Processing column: 100T
Renamed 100T to 100T | ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
Processing column: 105T
Renamed 105T to 105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก
Processing column: 35T
Renamed 35T to 35T | ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
Processing column: 36T
Renamed 36T to 36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
Processing column: 37T
Renamed 37T to 37T | ต.พระบาท อ.เมือง จ.ลำปาง
Processing column: 38T
Renamed 38T to 38T | ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
Processing column: 39T
Renamed 39T to 39T | ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
Processing column: 40T
Renamed 40T to 40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
Processing column: 41T
Renamed 41T to 41T | ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
Processing column: 57T
Renamed 57T to 57T | ต.เวียง อ.เมือง จ.เชียงราย
Processing column: 73T
Renamed 73T to 73T | ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
Processing column: 58T
Renamed 58T to 58T | ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
Processing column: 67T
Renamed 67T to 67T | ต.ในเวียง อ.เมือง จ.น่าน
Processing column: 75T
Renamed 75T to 75T | ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
Processing column: 68T
Renamed 68T to 68T | ต.บ้านกลาง อ.เมือง จ.ลำพูน
Processing column: 69T
Renamed 69T to 69T | ต.นาจักร อ.เมือง จ. แพร่
Processing column: 70T
Renamed 70T to 70T | ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
Processing column: 76T
Renamed 76T to 76T | ต.แม่ปะ อ.แม่สอด จ.ตาก
Processing column: 86T
Renamed 86T to 86T | ต.ในเมือง อ.เมือง จ.พิษณุโลก
Processing column: 92T
Renamed 92T to 92T | ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
Processing column: 94T
Renamed 94T to 94T | ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
Processing column: 95T
Renamed 95T to 95T | ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
Processing column: 96T
Renamed 96T to 96T | ต.ธานี อ.เมือง จ.สุโขทัย
Processing column: 97T
Renamed 97T to 97T | ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
Processing column: 98T
Renamed 98T to 98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
Processing column: 42T
Renamed 42T to 42T | ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
Processing column: 43T
Renamed 43T to 43T | ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
Processing column: 44T
Renamed 44T to 44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
Processing column: 62T
Renamed 62T to 62T | ต.บางนาค อ.เมือง จ.นราธิวาส
Processing column: 63T
Renamed 63T to 63T | ต.สะเตง อ.เมือง จ.ยะลา
Processing column: 78T
Renamed 78T to 78T | ต.เบตง อ.เบตง จ.ยะลา
Processing column: 80T
Renamed 80T to 80T | ต.พิมาน อ.เมือง. จ.สตูล
Processing column: 89T
Renamed 89T to 89T | ต.คลัง อ.เมือง จ.นครศรีธรรมราช
Processing column: 93T
Renamed 93T to 93T | ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง
Processing column: Date
Processing column: 02T
Renamed 02T to 02T | แขวงหิรัญรูจี เขตธนบุรี กทม.
Processing column: 05T
Renamed 05T to 05T | แขวงบางนา เขตบางนา กทม.
Processing column: 10T
Renamed 10T to 10T | แขวงคลองจั่น เขตบางกะปิ กทม.
Processing column: 11T
Renamed 11T to 11T | แขวงดินแดง เขตดินแดง กทม.
Processing column: 12T
Renamed 12T to 12T | แขวงช่องนนทรี เขตยานนาวา กทม.
Processing column: 59T
Renamed 59T to 59T | แขวงพญาไท เขตพญาไท กทม.
Processing column: 61T
Renamed 61T to 61T | แขวงพลับพลา เขตวังทองหลาง กทม.
Processing column: 03T
Renamed 03T to 03T | ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.
Processing column: 50T
Renamed 50T to 50T | ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
Processing column: 52T
Renamed 52T to 52T | ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.
Processing column: 53T
Renamed 53T to 53T | ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.
Processing column: 54T
Renamed 54T to 54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
Processing column: 08T
Renamed 08T to 08T | ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
Processing column: 16T
Renamed 16T to 16T | ต.บางโปรง อ.เมือง จ.สมุทรปราการ
Processing column: 17T
Renamed 17T to 17T | ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
Processing column: 18T
Renamed 18T to 18T | ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
Processing column: 19T
Renamed 19T to 19T | ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
Processing column: 13T
Renamed 13T to 13T | ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
Processing column: 22T
Renamed 22T to 22T | ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
Processing column: 14T
Renamed 14T to 14T | ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
Processing column: 27T
Renamed 27T to 27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร
Processing column: 20T
Renamed 20T to 20T | ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
Processing column: 81T
Renamed 81T to 81T | ต.นครปฐม อ.เมือง จ.นครปฐม
Processing column: 21T
Renamed 21T to 21T | ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา
Processing column: 24T
Renamed 24T to 24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
Processing column: 25T
Renamed 25T to 25T | ต.ปากเพรียว อ.เมือง จ.สระบุรี
Processing column: 26T
Renamed 26T to 26T | ต.หน้าเมือง อ.เมือง จ.ราชบุรี
Processing column: 79T
Renamed 79T to 79T | ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
Processing column: 84T
Renamed 84T to 84T | ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
Processing column: 85T
Renamed 85T to 85T | ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
Processing column: 99T
Renamed 99T to 99T | ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
Processing column: 103T
Renamed 103T to 103T | ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
Processing column: 104T
Renamed 104T to 104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี
Processing column: 46T
Renamed 46T to 46T | ต.ในเมือง อ.เมือง จ.ขอนแก่น
Processing column: 47T
Renamed 47T to 47T | ต.ในเมือง อ.เมือง จ.นครราชสีมา
Processing column: 72T
Renamed 72T to 72T | ต.กุดป่อง อ.เมือง จ.เลย
Processing column: 82T
Renamed 82T to 82T | ต.มีชัย อ.เมือง จ.หนองคาย
Processing column: 83T
Renamed 83T to 83T | ต.ในเมือง อ.เมือง จ.อุบลราชธานี
Processing column: 88T
Renamed 88T to 88T | ต.ในเมือง อ.เมือง จ.นครพนม
Processing column: 90T
Renamed 90T to 90T | ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
Processing column: 91T
Renamed 91T to 91T | ต.หมากแข้ง อ.เมือง จ.อุดรธานี
Processing column: 101T
Renamed 101T to 101T | ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
Processing column: 102T
Renamed 102T to 102T | ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
Processing column: 106T
Renamed 106T to 106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
Processing column: 107T
Renamed 107T to 107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
Processing column: 108T
Renamed 108T to 108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ
Processing column: 109T
Renamed 109T to 109T | ต.ในเมือง อ.เมือง จ.ยโสธร
Processing column: 110T
Renamed 110T to 110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
Processing column: 111T
Renamed 111T to 111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์
Processing column: 112T
Renamed 112T to 112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ
Processing column: 28T
Renamed 28T to 28T | ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
Processing column: 29T
Renamed 29T to 29T | ต.มาบตาพุด อ.เมือง จ.ระยอง
Processing column: 30T
Renamed 30T to 30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง
Processing column: 31T
Renamed 31T to 31T | ต.ห้วยโป่ง อ.เมือง จ.ระยอง
Processing column: 74T
Renamed 74T to 74T | ต.เนินพระ อ.เมือง จ.ระยอง
Processing column: 32T
Renamed 32T to 32T | ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
Processing column: 33T
Renamed 33T to 33T | ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
Processing column: 34T
Renamed 34T to 34T | ต.บ้านสวน อ.เมือง จ.ชลบุรี
Processing column: 60T
Renamed 60T to 60T | ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
Processing column: 71T
Renamed 71T to 71T | ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
Processing column: 77T
Renamed 77T to 77T | ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
Processing column: 87T
Renamed 87T to 87T | ต.บางพระ อ.เมือง จ.ตราด
Processing column: 100T
Renamed 100T to 100T | ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
Processing column: 105T
Renamed 105T to 105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก
Processing column: 35T
Renamed 35T to 35T | ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
Processing column: 36T
Renamed 36T to 36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
Processing column: 37T
Renamed 37T to 37T | ต.พระบาท อ.เมือง จ.ลำปาง
Processing column: 38T
Renamed 38T to 38T | ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
Processing column: 39T
Renamed 39T to 39T | ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
Processing column: 40T
Renamed 40T to 40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
Processing column: 41T
Renamed 41T to 41T | ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
Processing column: 57T
Renamed 57T to 57T | ต.เวียง อ.เมือง จ.เชียงราย
Processing column: 73T
Renamed 73T to 73T | ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
Processing column: 58T
Renamed 58T to 58T | ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
Processing column: 67T
Renamed 67T to 67T | ต.ในเวียง อ.เมือง จ.น่าน
Processing column: 75T
Renamed 75T to 75T | ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
Processing column: 68T
Renamed 68T to 68T | ต.บ้านกลาง อ.เมือง จ.ลำพูน
Processing column: 69T
Renamed 69T to 69T | ต.นาจักร อ.เมือง จ. แพร่
Processing column: 70T
Renamed 70T to 70T | ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
Processing column: 76T
Renamed 76T to 76T | ต.แม่ปะ อ.แม่สอด จ.ตาก
Processing column: 86T
Renamed 86T to 86T | ต.ในเมือง อ.เมือง จ.พิษณุโลก
Processing column: 92T
Renamed 92T to 92T | ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
Processing column: 94T
Renamed 94T to 94T | ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
Processing column: 95T
Renamed 95T to 95T | ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
Processing column: 96T
Renamed 96T to 96T | ต.ธานี อ.เมือง จ.สุโขทัย
Processing column: 97T
Renamed 97T to 97T | ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
Processing column: 98T
Renamed 98T to 98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
Processing column: 42T
Renamed 42T to 42T | ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
Processing column: 43T
Renamed 43T to 43T | ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
Processing column: 44T
Renamed 44T to 44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
Processing column: 62T
Renamed 62T to 62T | ต.บางนาค อ.เมือง จ.นราธิวาส
Processing column: 63T
Renamed 63T to 63T | ต.สะเตง อ.เมือง จ.ยะลา
Processing column: 78T
Renamed 78T to 78T | ต.เบตง อ.เบตง จ.ยะลา
Processing column: 80T
Renamed 80T to 80T | ต.พิมาน อ.เมือง. จ.สตูล
Processing column: 89T
Renamed 89T to 89T | ต.คลัง อ.เมือง จ.นครศรีธรรมราช
Processing column: 93T
Renamed 93T to 93T | ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง
Processing column: Date
Processing column: 02T
Renamed 02T to 02T | แขวงหิรัญรูจี เขตธนบุรี กทม.
Processing column: 05T
Renamed 05T to 05T | แขวงบางนา เขตบางนา กทม.
Processing column: 10T
Renamed 10T to 10T | แขวงคลองจั่น เขตบางกะปิ กทม.
Processing column: 11T
Renamed 11T to 11T | แขวงดินแดง เขตดินแดง กทม.
Processing column: 12T
Renamed 12T to 12T | แขวงช่องนนทรี เขตยานนาวา กทม.
Processing column: 59T
Renamed 59T to 59T | แขวงพญาไท เขตพญาไท กทม.
Processing column: 61T
Renamed 61T to 61T | แขวงพลับพลา เขตวังทองหลาง กทม.
Processing column: 03T
Renamed 03T to 03T | ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.
Processing column: 50T
Renamed 50T to 50T | ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
Processing column: 52T
Renamed 52T to 52T | ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.
Processing column: 53T
Renamed 53T to 53T | ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.
Processing column: 54T
Renamed 54T to 54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
Processing column: 08T
Renamed 08T to 08T | ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
Processing column: 16T
Renamed 16T to 16T | ต.บางโปรง อ.เมือง จ.สมุทรปราการ
Processing column: 17T
Renamed 17T to 17T | ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
Processing column: 18T
Renamed 18T to 18T | ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
Processing column: 19T
Renamed 19T to 19T | ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
Processing column: 13T
Renamed 13T to 13T | ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
Processing column: 22T
Renamed 22T to 22T | ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
Processing column: 14T
Renamed 14T to 14T | ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
Processing column: 27T
Renamed 27T to 27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร
Processing column: 20T
Renamed 20T to 20T | ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
Processing column: 81T
Renamed 81T to 81T | ต.นครปฐม อ.เมือง จ.นครปฐม
Processing column: 21T
Renamed 21T to 21T | ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา
Processing column: 24T
Renamed 24T to 24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
Processing column: 25T
Renamed 25T to 25T | ต.ปากเพรียว อ.เมือง จ.สระบุรี
Processing column: 26T
Renamed 26T to 26T | ต.หน้าเมือง อ.เมือง จ.ราชบุรี
Processing column: 79T
Renamed 79T to 79T | ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
Processing column: 84T
Renamed 84T to 84T | ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
Processing column: 85T
Renamed 85T to 85T | ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
Processing column: 99T
Renamed 99T to 99T | ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
Processing column: 103T
Renamed 103T to 103T | ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
Processing column: 46T
Renamed 46T to 46T | ต.ในเมือง อ.เมือง จ.ขอนแก่น
Processing column: 47T
Renamed 47T to 47T | ต.ในเมือง อ.เมือง จ.นครราชสีมา
Processing column: 72T(ใหม่)
Processing column: 82T
Renamed 82T to 82T | ต.มีชัย อ.เมือง จ.หนองคาย
Processing column: 83T
Renamed 83T to 83T | ต.ในเมือง อ.เมือง จ.อุบลราชธานี
Processing column: 88T
Renamed 88T to 88T | ต.ในเมือง อ.เมือง จ.นครพนม
Processing column: 90T
Renamed 90T to 90T | ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
Processing column: 91T
Renamed 91T to 91T | ต.หมากแข้ง อ.เมือง จ.อุดรธานี
Processing column: 101T
Renamed 101T to 101T | ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
Processing column: 102T
Renamed 102T to 102T | ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
Processing column: 28T
Renamed 28T to 28T | ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
Processing column: 29T
Renamed 29T to 29T | ต.มาบตาพุด อ.เมือง จ.ระยอง
Processing column: 30T
Renamed 30T to 30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง
Processing column: 31T
Renamed 31T to 31T | ต.ห้วยโป่ง อ.เมือง จ.ระยอง
Processing column: 74T
Renamed 74T to 74T | ต.เนินพระ อ.เมือง จ.ระยอง
Processing column: 32T
Renamed 32T to 32T | ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
Processing column: 33T
Renamed 33T to 33T | ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
Processing column: 34T
Renamed 34T to 34T | ต.บ้านสวน อ.เมือง จ.ชลบุรี
Processing column: 60T
Renamed 60T to 60T | ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
Processing column: 71T
Renamed 71T to 71T | ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
Processing column: 77T
Renamed 77T to 77T | ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
Processing column: 87T
Renamed 87T to 87T | ต.บางพระ อ.เมือง จ.ตราด
Processing column: 100T
Renamed 100T to 100T | ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
Processing column: 35T
Renamed 35T to 35T | ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
Processing column: 36T
Renamed 36T to 36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
Processing column: 37T
Renamed 37T to 37T | ต.พระบาท อ.เมือง จ.ลำปาง
Processing column: 38T
Renamed 38T to 38T | ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
Processing column: 39T
Renamed 39T to 39T | ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
Processing column: 40T
Renamed 40T to 40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
Processing column: 41T
Renamed 41T to 41T | ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
Processing column: 57T
Renamed 57T to 57T | ต.เวียง อ.เมือง จ.เชียงราย
Processing column: 73T
Renamed 73T to 73T | ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
Processing column: 58T
Renamed 58T to 58T | ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
Processing column: 67T
Renamed 67T to 67T | ต.ในเวียง อ.เมือง จ.น่าน
Processing column: 75T
Renamed 75T to 75T | ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
Processing column: 68T
Renamed 68T to 68T | ต.บ้านกลาง อ.เมือง จ.ลำพูน
Processing column: 69T
Renamed 69T to 69T | ต.นาจักร อ.เมือง จ. แพร่
Processing column: 70T
Renamed 70T to 70T | ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
Processing column: 76T
Renamed 76T to 76T | ต.แม่ปะ อ.แม่สอด จ.ตาก
Processing column: 86T
Renamed 86T to 86T | ต.ในเมือง อ.เมือง จ.พิษณุโลก
Processing column: 92T

In [36]:
# dfs_pm[2011]

In [37]:
# Combine all years into a single DataFrame
df_all_years = pd.concat(dfs_pm.values(), keys=dfs_pm.keys(), names=['Year', 'Row'])

# Reset the index to make it easier to work with
df_all_years.reset_index(level=0, inplace=True)

# df_all_years

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_2725/3551904210.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_all_years.reset_index(level=0, inplace=True)

In [38]:
#check size
print(dfs_pm[2011].shape)
print(dfs_pm[2012].shape)
print(dfs_pm[2013].shape)
print(dfs_pm[2014].shape)
print(dfs_pm[2015].shape)
print(dfs_pm[2016].shape)
print(dfs_pm[2017].shape)
print(dfs_pm[2018].shape)
print(dfs_pm[2019].shape)
print(dfs_pm[2020].shape)
print(dfs_pm[2021].shape)
print(dfs_pm[2022].shape)
print(dfs_pm[2023].shape)
print(dfs_pm[2024].shape)

print(df_all_years.shape)

print("-"*10)
size = 0
for i in range(2011, 2025):
    size += dfs_pm[i].shape[0]  # Add the number of rows for each DataFrame

print(size)

(366, 4)
(366, 6)
(365, 8)
(365, 11)
(365, 13)
(366, 20)
(365, 27)
(365, 54)
(365, 67)
(366, 69)
(365, 79)
(365, 88)
(367, 97)
(366, 97)
(5117, 114)
----------
5117

In [39]:
dfs_pm[2011].columns

Index(['Date', '54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.',
       '36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่',
       '30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง'],
      dtype='object')

In [40]:
df_all_years.tail()

,Year,Date,54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.,36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่,30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง,24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี,44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา,27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร,40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง,61T | แขวงพลับพลา เขตวังทองหลาง กทม.,...,98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี,104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี,106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ,107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์,108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ,109T | ต.ในเมือง อ.เมือง จ.ยโสธร,110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ,111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์,112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ,105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก
Row,,,,,,,,,,,,,,,,,,,,,
361,2024,2024-12-27 00:00:00,44.5,23.6,24.4,35.6,12.0,63.6,27.3,34.6,...,51.2,30.3,10.7,23.5,20.7,22.9,16.9,12.4,10.1,36.9
362,2024,2024-12-28 00:00:00,27.7,17.4,13.4,25.3,9.7,43.8,23.7,22.6,...,37.8,24.4,10.1,20.4,19.3,22.7,17.4,9.7,9.8,14.4
363,2024,2024-12-29 00:00:00,23.3,20.1,12.3,20.8,10.1,30.9,20.2,20.1,...,24.9,25.1,15.1,32.9,17.9,35.3,29.5,23.2,22.5,12.0
364,2024,2024-12-30 00:00:00,33.4,23.1,23.4,29.6,14.0,49.2,20.9,27.1,...,37.9,38.6,24.9,32.2,27.1,38.9,31.8,25.2,30.2,19.6
365,2024,2024-12-31 00:00:00,34.9,21.5,25.6,37.1,15.6,38.9,22.0,29.5,...,35.2,32.0,20.4,33.9,23.3,33.9,28.6,19.5,20.0,23.8

In [41]:
# Drop the last two rows
df_all_years = df_all_years.iloc[:-2]

In [42]:
df_all_years.tail()

,Year,Date,54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.,36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่,30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง,24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี,44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา,27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร,40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง,61T | แขวงพลับพลา เขตวังทองหลาง กทม.,...,98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี,104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี,106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ,107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์,108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ,109T | ต.ในเมือง อ.เมือง จ.ยโสธร,110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ,111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์,112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ,105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก
Row,,,,,,,,,,,,,,,,,,,,,
359,2024,2024-12-25 00:00:00,44.1,26.8,20.6,42.3,16.0,60.4,29.0,32.0,...,54.0,43.5,28.6,45.2,36.6,45.5,39.9,33.2,34.3,20.8
360,2024,2024-12-26 00:00:00,43.6,24.3,26.7,50.3,16.6,59.1,29.2,37.1,...,51.8,56.5,18.2,37.6,37.8,34.7,26.1,25.1,23.7,39.8
361,2024,2024-12-27 00:00:00,44.5,23.6,24.4,35.6,12.0,63.6,27.3,34.6,...,51.2,30.3,10.7,23.5,20.7,22.9,16.9,12.4,10.1,36.9
362,2024,2024-12-28 00:00:00,27.7,17.4,13.4,25.3,9.7,43.8,23.7,22.6,...,37.8,24.4,10.1,20.4,19.3,22.7,17.4,9.7,9.8,14.4
363,2024,2024-12-29 00:00:00,23.3,20.1,12.3,20.8,10.1,30.9,20.2,20.1,...,24.9,25.1,15.1,32.9,17.9,35.3,29.5,23.2,22.5,12.0

In [43]:
df_all_years.shape

(5115, 114)

In [44]:
df_all_years = df_all_years.dropna(how='all', subset=df_all_years.columns[1:])
df_all_years.shape

(5113, 114)

In [45]:
df_all_years.to_csv("../../data/a1/PM2.5_all_years.csv", index=False)

In [46]:
pd.set_option('display.max_rows', None)

df_column = pd.DataFrame(df_all_years.columns)

display(df_column)

                                                     0
0                                                 Year
1                                                 Date
2         54T | ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.
3                  36T | ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่
4                    30T | ต.ท่าประดู่ อ.เมือง จ.ระยอง
5      24T | ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี
6                    44T | ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา
7                   27T | ต.มหาชัย อ.เมือง จ.สมุทรสาคร
8                    40T | ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
9                 61T | แขวงพลับพลา เขตวังทองหลาง กทม.
10                 26T | ต.หน้าเมือง อ.เมือง จ.ราชบุรี
11                   46T | ต.ในเมือง อ.เมือง จ.ขอนแก่น
12                                                59T
13                                                54T
14                                                24T
15                                                26T
16                                                30T
17                32T | ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี
18                                                36T
19                                                44T
20                       05T | แขวงบางนา เขตบางนา กทม.
21                       59T | แขวงพญาไท เขตพญาไท กทม.
22                                                61T
23                                                52T
24                                                08T
25                                                27T
26               35T | ต.ช้างเผือก อ.เมือง จ.เชียงใหม่
27           75T | ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
28                        76T | ต.แม่ปะ อ.แม่สอด จ.ตาก
29                                                77T
30   50T | ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.
31   52T | ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบ...
32   53T | ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองห...
33           08T | ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ
34           19T | ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ
35                   62T | ต.บางนาค อ.เมือง จ.นราธิวาส
36                        63T | ต.สะเตง อ.เมือง จ.ยะลา
37            77T | ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี
38               79T | ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี
39                       80T | ต.พิมาน อ.เมือง. จ.สตูล
40                  10T | แขวงคลองจั่น เขตบางกะปิ กทม.
41                     11T | แขวงดินแดง เขตดินแดง กทม.
42   03T | ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเที...
43           14T | ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร
44              17T | ต.ตลาด อ.พระประแดง จ.สมุทรปราการ
45                18T | ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ
46             20T | ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี
47   21T | ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรี...
48                25T | ต.ปากเพรียว อ.เมือง จ.สระบุรี
49                    29T | ต.มาบตาพุด อ.เมือง จ.ระยอง
50                    31T | ต.ห้วยโป่ง อ.เมือง จ.ระยอง
51                   33T | ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี
52                    34T | ต.บ้านสวน อ.เมือง จ.ชลบุรี
53                      37T | ต.พระบาท อ.เมือง จ.ลำปาง
54                    38T | ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
55                    39T | ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
56                41T | ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์
57           42T | ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี
58                    57T | ต.เวียง อ.เมือง จ.เชียงราย
59                  58T | ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
60                      67T | ต.ในเวียง อ.เมือง จ.น่าน
61                    68T | ต.บ้านกลาง อ.เมือง จ.ลำพูน
62                      69T | ต.นาจักร อ.เมือง จ. แพร่
63               70T | ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา
64          71T | ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว
65                       72T | ต.กุดป่อง อ.เมือง จ.เลย
66              73T | ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
67                  02T | แขวงหิรัญรูจี เขตธนบุรี กทม.
68                 12T | แขวงช่องนนทรี เขตยานนาวา กทม.
69                  13T | ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี
70               16T | ต.บางโปรง อ.เมือง จ.สมุทรปราการ
71                 22T | ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี
72                   28T | ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง
73                   43T | ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต
74                47T | ต.ในเมือง อ.เมือง จ.นครราชสีมา
75              60T | ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา
76                                                70T*
77                                               70T**
78                     74T | ต.เนินพระ อ.เมือง จ.ระยอง
79                          78T | ต.เบตง อ.เบตง จ.ยะลา
80                     81T | ต.นครปฐม อ.เมือง จ.นครปฐม
81                     82T | ต.มีชัย อ.เมือง จ.หนองคาย
82               83T | ต.ในเมือง อ.เมือง จ.อุบลราชธานี
83               84T | ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม
84               85T | ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี
85                                           72T(เก่า)
86                                           72T(ใหม่)
87                    88T | ต.ในเมือง อ.เมือง จ.นครพนม
88                  90T | ต.ธาตุนาเวง อ.เมือง จ.สกลนคร
89                 91T | ต.หมากแข้ง อ.เมือง จ.อุดรธานี
90                       87T | ต.บางพระ อ.เมือง จ.ตราด
91                  86T | ต.ในเมือง อ.เมือง จ.พิษณุโลก
92                  92T | ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์
93                89T | ต.คลัง อ.เมือง จ.นครศรีธรรมราช
94                 93T | ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง
95            99T | ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี
96          103T | ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์
97                 101T | ต.เสม็ด อ.เมือง  จ.บุรีรัมย์
98        102T | ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร
99         100T | ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี
100       94T | ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร
101             95T | ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร
102                     96T | ต.ธานี อ.เมือง จ.สุโขทัย
103       97T | ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์
104     98T | ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี
105                104T | ต.บางมัญ อ.เมือง จ.สิงห์บุรี
106                   106T | ต.บึงกาฬ อ.เมือง จ.บึงกาฬ
107             107T | ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์
108                 108T | ต.ในเมือง อ.เมือง จ.ชัยภูมิ
109                   109T | ต.ในเมือง อ.เมือง จ.ยโสธร
110                 110T | ต.บุ่ง อ.เมือง จ.อำนาจเจริญ
111               111T | ต.นอกเมือง อ.เมือง จ.สุรินทร์
112                112T | ต.หนองครก อ.เมือง จ.ศรีสะเกษ
113                105T | ต.บ้านใหญ่ อ.เมือง จ.นครนายก