In [1]:
import numpy as np
import pandas as pd

In [3]:
df_check = pd.read_excel("../../data/boundaries/tha_adminboundaries_tabulardata.xlsx", sheet_name='ADM1')

In [4]:
df_check

,ADM1_EN,ADM1_TH,ADM1_PCODE,ADM1_REF,ADM1ALT1_EN,ADM1ALT2_EN,ADM1ALT1_TH,ADM1ALT2_TH,ADM0_EN,ADM0_TH,ADM0_PCODE,DATE,VALIDON,VALIDTO,AREA_SQKM
0,Bangkok,กรุงเทพมหานคร,TH10,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,1571.371336
1,Samut Prakan,สมุทรปราการ,TH11,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,949.001113
2,Nonthaburi,นนทบุรี,TH12,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,636.542920
3,Pathum Thani,ปทุมธานี,TH13,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,1517.386645
4,Phra Nakhon Si Ayutthaya,พระนครศรีอยุธยา,TH14,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,2553.360962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Trang,ตรัง,TH92,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,4709.743170
73,Phatthalung,พัทลุง,TH93,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,3860.383277
74,Pattani,ปัตตานี,TH94,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,1966.320520
75,Yala,ยะลา,TH95,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,4472.740198
76,Narathiwat,นราธิวาส,TH96,NaN,NaN,NaN,NaN,NaN,Thailand,ประเทศไทย,TH,2019-02-18,2022-01-22,NaN,4487.557450

In [5]:
df_check = df_check[['ADM1_EN', 'ADM1_TH', 'AREA_SQKM']]
df_check

                     ADM1_EN          ADM1_TH    AREA_SQKM
0                    Bangkok    กรุงเทพมหานคร  1571.371336
1               Samut Prakan      สมุทรปราการ   949.001113
2                 Nonthaburi          นนทบุรี   636.542920
3               Pathum Thani         ปทุมธานี  1517.386645
4   Phra Nakhon Si Ayutthaya  พระนครศรีอยุธยา  2553.360962
..                       ...              ...          ...
72                     Trang             ตรัง  4709.743170
73               Phatthalung           พัทลุง  3860.383277
74                   Pattani          ปัตตานี  1966.320520
75                      Yala             ยะลา  4472.740198
76                Narathiwat         นราธิวาส  4487.557450

[77 rows x 3 columns]

In [6]:
from math import pi

In [7]:
area = 0
i = 0
target = 100 * 1.2
while not (area > target):
    area = pi * (i**2)
    i = i+0.5

print(area)

132.73228961416876

In [8]:
df_check.rename(columns={"ADM1_EN": "English_name"}, inplace=True)
df_check.rename(columns={"ADM1_TH": "Thai_name"}, inplace = True)
df_check.rename(columns={"AREA_SQKM": "AREA"}, inplace = True)

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/2392656376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check.rename(columns={"ADM1_EN": "English_name"}, inplace=True)
/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/2392656376.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check.rename(columns={"ADM1_TH": "Thai_name"}, inplace = True)
/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/2392656376.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check.rename(columns={"AREA_SQKM": "AREA"}, inplace = True)

In [9]:
df_check

                English_name        Thai_name         AREA
0                    Bangkok    กรุงเทพมหานคร  1571.371336
1               Samut Prakan      สมุทรปราการ   949.001113
2                 Nonthaburi          นนทบุรี   636.542920
3               Pathum Thani         ปทุมธานี  1517.386645
4   Phra Nakhon Si Ayutthaya  พระนครศรีอยุธยา  2553.360962
..                       ...              ...          ...
72                     Trang             ตรัง  4709.743170
73               Phatthalung           พัทลุง  3860.383277
74                   Pattani          ปัตตานี  1966.320520
75                      Yala             ยะลา  4472.740198
76                Narathiwat         นราธิวาส  4487.557450

[77 rows x 3 columns]

In [10]:
df_check[["English_name", "Thai_name"]].drop_duplicates()

                English_name        Thai_name
0                    Bangkok    กรุงเทพมหานคร
1               Samut Prakan      สมุทรปราการ
2                 Nonthaburi          นนทบุรี
3               Pathum Thani         ปทุมธานี
4   Phra Nakhon Si Ayutthaya  พระนครศรีอยุธยา
..                       ...              ...
72                     Trang             ตรัง
73               Phatthalung           พัทลุง
74                   Pattani          ปัตตานี
75                      Yala             ยะลา
76                Narathiwat         นราธิวาส

[77 rows x 2 columns]

In [16]:
df_pmmap = pd.read_csv("../../data/a1/PM_map.csv")
df_pmmap

,รหัสสถานี,ชื่อสถานี,รายละเอียดจุดติดตั้งสถานี,จังหวัด,english_name,adm1__id
0,02T,แขวงหิรัญรูจี เขตธนบุรี กทม.,มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา,กทม.,Bangkok Metropolis,3.0
1,05T,แขวงบางนา เขตบางนา กทม.,กรมอุตุนิยมวิทยา,กทม.,Bangkok Metropolis,3.0
2,10T,แขวงคลองจั่น เขตบางกะปิ กทม.,เคหะชุมชนคลองจั่น,กทม.,Bangkok Metropolis,3.0
3,11T,แขวงดินแดง เขตดินแดง กทม.,สนามกีฬาเคหะชุมชนห้วยขวาง,กทม.,Bangkok Metropolis,3.0
4,12T,แขวงช่องนนทรี เขตยานนาวา กทม.,โรงเรียนนนทรีวิทยา,กทม.,Bangkok Metropolis,3.0
5,59T,แขวงพญาไท เขตพญาไท กทม.,กรมประชาสัมพันธ์,กทม.,Bangkok Metropolis,3.0
6,61T,แขวงพลับพลา เขตวังทองหลาง กทม.,โรงเรียนบดินทรเดชา (สิงห์ สิงหเสนี),กทม.,Bangkok Metropolis,3.0
7,03T,ริมถนนกาญจนาภิเษก แขวงแสมดำ เขตบางขุนเทียน กทม.,ริมถนนกาญจนาภิเษก,กทม.,Bangkok Metropolis,3.0
8,50T,ริมถนนพระรามสี่ แขวงปทุมวัน เขตปทุมวัน กทม.,โรงพยาบาลจุฬาลงกรณ์,กทม.,Bangkok Metropolis,3.0
9,52T,ริมถนนอินทรพิทักษ์ แขวงบางยี่เรือ เขตธนบุรี กทม.,สถานีไฟฟ้าย่อยธนบุรี,กทม.,Bangkok Metropolis,3.0
10,53T,ริมถนนลาดพร้าว แขวงวังทองหลาง เขตวังทองหลาง กทม.,สถานีตำรวจนครบาลโชคชัย,กทม.,Bangkok Metropolis,3.0
11,54T,ริมถนนดินแดง แขวงดินแดง เขตดินแดง กทม.,เคหะชุมชนดินแดง,กทม.,Bangkok Metropolis,3.0
12,08T,ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ,ศูนย์ฟื้นฟูอาชีพคนพิการและทุพพลภาพพระประแดง,จ.สมุทรปราการ,Samut Prakan,57.0
13,16T,ต.บางโปรง อ.เมือง จ.สมุทรปราการ,โรงไฟฟ้าพระนครใต้,จ.สมุทรปราการ,Samut Prakan,57.0
14,17T,ต.ตลาด อ.พระประแดง จ.สมุทรปราการ,บ้านพักกรมอุตสาหกรรมพื้นฐานและการเหมืองแร่,จ.สมุทรปราการ,Samut Prakan,57.0
15,18T,ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ,ศาลากลางจังหวัดสมุทรปราการ,จ.สมุทรปราการ,Samut Prakan,57.0
16,19T,ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ,เคหะชุมชนเมืองใหม่บางพลี,จ.สมุทรปราการ,Samut Prakan,57.0
17,13T,ต.ตลาดขวัญ อ.เมือง จ.นนทบุรี,กรมควบคุมโรค,จ.นนทบุรี,Nonthaburi,36.0
18,22T,ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี,มหาวิทยาลัยสุโขทัยธรรมาธิราช,จ.นนทบุรี,Nonthaburi,36.0
19,14T,ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร,หน่วยบริการตำรวจทางหลวงศรีสำราญ สมุทรสาคร,จ.สมุทรสาคร,Samut Sakhon,58.0
20,27T,ต.มหาชัย อ.เมือง จ.สมุทรสาคร,โรงเรียนสมุทรสาครวิทยาลัย,จ.สมุทรสาคร,Samut Sakhon,58.0
21,20T,ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี,มหาวิทยาลัยกรุงเทพ (วิทยาเขตรังสิต),จ.ปทุมธานี,Pathum Thani,37.0
22,81T,ต.นครปฐม อ.เมือง จ.นครปฐม,อ่างเก็บน้ำประปา นครปฐม,จ.นครปฐม,Nakhon Pathom,27.0
23,21T,ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา,โรงเรียนอยุธยาวิทยาลัย,จ.พระนครศรีอยุธยา,Phra Nakhon Si Ayutthaya,46.0
24,24T,ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี,สถานีตำรวจภูธรตำบลหน้าพระลาน,NaN,NaN,NaN
25,25T,ต.ปากเพรียว อ.เมือง จ.สระบุรี,สถานีดับเพลิงพระลักษณ์,NaN,NaN,NaN
26,26T,ต.หน้าเมือง อ.เมือง จ.ราชบุรี,สำนักงานสิ่งแวดล้อมภาคที่ ๘ ราชบุรี,จ.ราชบุรี,Ratchaburi,52.0
27,79T,ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี,สถานีอุตุนิยมวิทยากาญจนบุรี,จ.กาญจนบุรี,Kanchanaburi,16.0
28,84T,ต.ลาดใหญ่ อ.เมือง จ.สมุทรสงคราม,สำนักงานสาธารณสุขจังหวัดสมุทรสงคราม,จ.สมุทรสงคราม,Samut Songkhram,59.0
29,85T,ต.ดอนกำยาน อ.เมือง จ.สุพรรณบุรี,สนามกีฬากลางจังหวัดสุพรรณบุรี,จ.สุพรรณบุรี,Suphan Buri,66.0
30,99T,ต.ทะเลชุบศร อ.เมืองลพบุรี จ.ลพบุรี,สถานีอุตุนิยมวิทยาลพบุรี,จ.ลพบุรี,Lop Buri,22.0
31,103T,ต.หัวหิน อ.หัวหิน จ.ประจวบคีรีขันธ์,สถานีตรวจอากาศหัวหิน สถานีอุตุนิยมวิทยาประจวบค...,จ.ประจวบคีรีขันธ์,Prachuap Khiri Khan,50.0
32,104T,ต.บางมัญ อ.เมือง จ.สิงห์บุรี,โรงเรียนสิงห์บุรี,จ.สิงห์บุรี,Sing Buri,63.0
33,46T,ต.ในเมือง อ.เมือง จ.ขอนแก่น,ส่วนอุทกวิทยา สำนักงานทรัพยากรน้ำภาค ๔ ขอนแก่น,จ.ขอนแก่น,Khon Kaen,17.0
34,47T,ต.ในเมือง อ.เมือง จ.นครราชสีมา,สถานีสูบน้ำเสียที่ ๑ ห้าแยกไอที นครราชสีมา,จ.นครราชสีมา,Nakhon Ratchasima,29.0
35,72T,ต.กุดป่อง อ.เมือง จ.เลย,สวนสาธารณะเฉลิมพระเกียรติ 60 พรรษา มหาราชินี,จ.เลย,Loei,21.0
36,82T,ต.มีชัย อ.เมือง จ.หนองคาย,สวนสาธารณะหนองถิ่น,จ.หนองคาย,Nong Khai,35.0
37,83T,ต.ในเมือง อ.เมือง จ.อุบลราชธานี,ศูนย์แสดงและจำหน่ายสินค้า OTOP จังหวัดอุบลราชธานี,จ.อุบลราชธานี,Ubon Ratchathani,72.0
38,88T,ต.ในเมือง อ.เมือง จ.นครพนม,สถานีอุตุนิยมวิทยานครพนม,จ.นครพนม,Nakhon Phanom,28.0
39,90T,ต.ธาตุนาเวง อ.เมือง จ.สกลนคร,สถานีอุตุนิยมวิทยาสกลนคร,จ.สกลนคร,Sakon Nakhon,56.0
40,91T,ต.หมากแข้ง อ.เมือง จ.อุดรธานี,บริเวณสวนสาธารณะหนองประจักษ์,จ.อุดรธานี,Udon Thani,73.0
41,101T,ต.เสม็ด อ.เมือง จ.บุรีรัมย์,ศาลากลางจังหวัดบุรีรัมย์,จ.บุรีรัมย์,Buri Ram,5.0
42,102T,ต.มุกดาหาร อ.เมืองมุกดาหาร จ.มุกดาหาร,สนามกีฬากลางจังหวัดมุกดาหาร,จ.มุกดาหาร,Mukdahan,25.0
43,106T,ต.บึงกาฬ อ.เมือง จ.บึงกาฬ,สวนสาธารณะหนองบึงกาฬ,จ.บึงกาฬ,Bueng Kan,4.0
44,107T,ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์,สวนสาธารณะดอนกลาง,จ.กาฬสินธุ์,Kalasin,14.0
45,108T,ต.ในเมือง อ.เมือง จ.ชัยภูมิ,สนามกีฬาเทศบาลเมืองชัยภูมิ,จ.ชัยภูมิ,Chaiyaphum,8.0
46,109T,ต.ในเมือง อ.เมือง จ.ยโสธร,สวนสาธารณะพญาแถน,จ.ยโสธร,Yasothon,77.0
47,110T,ต.บุ่ง อ.เมือง จ.อำนาจเจริญ,สำนักงานเทศบาลเมืองอำนาจเจริญ,จ.อำนาจเจริญ,Amnat Charoen,1.0
48,111T,ต.นอกเมือง อ.เมือง จ.สุรินทร์,สถานีอุตุนิยมวิทยาสุรินทร์,จ.สุรินทร์,Surin,68.0
49,112T,ต.หนองครก อ.เมือง จ.ศรีสะเกษ,สถานีอุตุนิยมวิทยาศรีสะเกษ,จ.ศรีสะเกษ,Si Sa Ket,62.0
50,28T,ต.ปลวกแดง อ.ปลวกแดง จ.ระยอง,สำนักงานสาธารณสุขอำเภอปลวกแดง,จ.ระยอง,Rayong,53.0
51,29T,ต.มาบตาพุด อ.เมือง จ.ระยอง,โรงพยาบาลส่งเสริมสุขภาพตำบลมาบตาพุด,จ.ระยอง,Rayong,53.0
52,30T,ต.ท่าประดู่ อ.เมือง จ.ระยอง,สำนักงานเกษตรจังหวัดระยอง,จ.ระยอง,Rayong,53.0
53,31T,ต.ห้วยโป่ง อ.เมือง จ.ระยอง,ศูนย์วิจัยพืชไร่ระยอง,จ.ระยอง,Rayong,53.0
54,74T,ต.เนินพระ อ.เมือง จ.ระยอง,ศูนย์ราชการจังหวัดระยอง,จ.ระยอง,Rayong,53.0
55,32T,ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี,สนามกีฬาเทศบาลแหลมฉบัง,จ.ชลบุรี,Chon Buri,12.0
56,33T,ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเขาหิน,จ.ชลบุรี,Chon Buri,12.0
57,34T,ต.บ้านสวน อ.เมือง จ.ชลบุรี,สำนักงานสิ่งแวดล้อมภาคที่ ๑๓ ชลบุรี,จ.ชลบุรี,Chon Buri,12.0
58,60T,ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา,สำนักงานเทศบาลตำบลทุ่งสะเดา,จ.ฉะเชิงเทรา,Chachoengsao,6.0
59,71T,ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว,สวนกาญจนาภิเษก ร.9 (ฝั่งสวนหิน),NaN,NaN,NaN
60,77T,ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี,ศาลาประชาคมบ้านบุยายใบ ปราจีนบุรี,จ.ปราจีนบุรี,Prachin Buri,49.0
61,87T,ต.บางพระ อ.เมือง จ.ตราด,สนามกีฬากลาง จังหวัดตราด,จ.ตราด,Trat,71.0
62,100T,ต.วัดใหม่ อ.เมืองจันทบุรี จ.จันทบุรี,สถานีอุตุนิยมวิทยาจันทบุรี,จ.จันทบุรี,Chanthaburi,9.0
63,105T,ต.บ้านใหญ่ อ.เมือง จ.นครนายก,สถานีอนามัยเทศบาลเมืองนครนายก,จ.นครนายก,Nakhon Nayok,26.0
64,35T,ต.ช้างเผือก อ.เมือง จ.เชียงใหม่,ศูนย์ราชการจังหวัดเชียงใหม่,จ.เชียงใหม่,Chiang Mai,10.0
65,36T,ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่,โรงเรียนยุพราชวิทยาลัย,จ.เชียงใหม่,Chiang Mai,10.0
66,37T,ต.พระบาท อ.เมือง จ.ลำปาง,สถานีอุตุนิยมวิทยาลำปาง,จ.ลำปาง,Lampang,19.0
67,38T,ต.สบป้าด อ.แม่เมาะ จ.ลำปาง,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสบป้าด,จ.ลำปาง,Lampang,19.0
68,39T,ต.บ้านดง อ.แม่เมาะ จ.ลำปาง,โรงพยาบาลส่งเสริมสุขภาพตำบลท่าสี,จ.ลำปาง,Lampang,19.0
69,40T,ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง,สำนักงานการประปาส่วนภูมิภาคอำเภอแม่เมาะ,จ.ลำปาง,Lampang,19.0
70,41T,ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์,โครงการชลประทานนครสวรรค์,จ.นครสวรรค์,Nakhon Sawan,30.0
71,57T,ต.เวียง อ.เมือง จ.เชียงราย,สำนักงานทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัดเ...,จ.เชียงราย,Chiang Rai,11.0
72,73T,ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย,สำนักงานสาธารณสุขอำเภอแม่สาย,จ.เชียงราย,Chiang Rai,11.0
73,58T,ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน,สำนักงานทรัพยากรธรรมชาติและสิ่งแวดล้อมจังหวัด ...,จ.แม่ฮ่องสอน,Mae Hong Son,23.0
74,67T,ต.ในเวียง อ.เมือง จ.น่าน,สำนักงานเทศบาลเมืองน่าน,จ.น่าน,Nan,32.0
75,75T,ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน,โรงพยาบาลเฉลิมพระเกียรติ น่าน,จ.น่าน,Nan,32.0
76,68T,ต.บ้านกลาง อ.เมือง จ.ลำพูน,สถานีอุตุนิยมวิทยาลำพูน,จ.ลำพูน,Lamphun,20.0
77,69T,ต.นาจักร อ.เมือง จ. แพร่,สถานีอุตุนิยมวิทยาแพร่,แพร่,Phrae,47.0
78,70,ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา,สนามกีฬาจังหวัดพะเยา,จ.พะเยา,Phayao,41.0
79,76T,ต.แม่ปะ อ.แม่สอด จ.ตาก,ศูนย์การศึกษานอกระบบอำเภอแม่สอด,จ.ตาก,Tak,69.0
80,86T,ต.ในเมือง อ.เมือง จ.พิษณุโลก,สวนชมน่าน บริเวณหน้าวิทยาลัยอาชีวศึกษาพิษณุโลก,จ.พิษณุโลก,Phitsanulok,45.0
81,92T,ต.ท่าอิฐ อ.เมือง จ.อุตรดิตถ์,บริเวณภายในพื้นที่สวนมหามงคลเฉลิมพระเกียรติพระ...,จ.อุตรดิตถ์,Uttaradit,75.0
82,94T,ต.ในเมือง อ.เมืองกำแพงเพชร จ.กำแพงเพชร,ลานอนุรักษ์วัฒนธรรมไทยสิริจิตอุทยาน,จ.กำแพงเพชร,Kamphaeng Phet,15.0
83,95T,ต.ในเมือง อ.เมืองพิจิตร จ.พิจิตร,สนามกีฬาจังหวัดพิจิตร,จ.พิจิตร,Phichit,44.0
84,96T,ต.ธานี อ.เมือง จ.สุโขทัย,สวนสาธารณะ ชุมชนเลอไทย,จ.สุโขทัย,Sukhothai,65.0
85,97T,ต.ในเมือง อ.เมืองเพชรบูรณ์ จ.เพชรบูรณ์,สวนสาธารณะเพชบุระ,จ.เพชรบูรณ์,Phetchabun,42.0
86,98T,ต.อุทัยใหม่ อ.เมืองอุทัยธานี จ.อุทัยธานี,สวนเฉลิมพระเกียรติพระบาทสมเด็จพระเจ้าอยู่หัว เ...,จ.อุทัยธานี,Uthai Thani,74.0
87,42T,ต.มะขามเตี้ย อ.เมือง จ.สุราษฏร์ธานี,สำนักงานสิ่งแวดล้อมภาคที่ ๑๔ สุราษฎร์ธานี,จ.สุราษฏร์ธานี,Surat Thani,67.0
88,43T,ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต,ศูนย์บริการสาธารณสุขเทศบาลนครภูเก็ต,จ.ภูเก็ต,Phuket,48.0
89,44T,ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา,เทศบาลนครหาดใหญ่,จ.สงขลา,Songkhla,64.0
90,62T,ต.บางนาค อ.เมือง จ.นราธิวาส,ศาลากลางจังหวัดนราธิวาส,จ.นราธิวาส,Narathiwat,33.0
91,63T,ต.สะเตง อ.เมือง จ.ยะลา,สวนสาธารณะสนามโรงพิธีช้างเผือก ยะลา,จ.ยะลา,Yala,76.0
92,78T,ต.เบตง อ.เบตง จ.ยะลา,ศูนย์พัฒนาเด็กเล็กเทศบาลเมืองเบตง,จ.ยะลา,Yala,76.0
93,80T,ต.พิมาน อ.เมือง. จ.สตูล,ศาลากลางจังหวัดสตูล,จ.สตูล,Satun,61.0
94,89T,ต.คลัง อ.เมือง จ.นครศรีธรรมราช,ศูนย์ฟื้นฟูสุขภาพผู้สูงอายุ,จ.นครศรีธรรมราช,Nakhon Si Thammarat,31.0
95,93T,ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง,วิทยาลัยสารพัดช่างตรัง,จ.ตรัง,Trang,70.0

In [17]:
df_check.loc[df_check["English_name"] == "Bangkok", "English_name"] = "Bangkok Metropolis"
df_check

                English_name        Thai_name          AREA
0         Bangkok Metropolis    กรุงเทพมหานคร   1571.371336
1               Samut Prakan      สมุทรปราการ    949.001113
2                 Nonthaburi          นนทบุรี    636.542920
3               Pathum Thani         ปทุมธานี   1517.386645
4   Phra Nakhon Si Ayutthaya  พระนครศรีอยุธยา   2553.360962
5                  Ang Thong          อ่างทอง    944.216921
6                   Lop Buri           ลพบุรี   6491.816312
7                  Sing Buri        สิงห์บุรี    818.192131
8                   Chai Nat           ชัยนาท   2486.567838
9                   Saraburi          สระบุรี   3481.759648
10                 Chon Buri           ชลบุรี   4504.763605
11                    Rayong            ระยอง   3682.137154
12               Chanthaburi         จันทบุรี   6403.634178
13                      Trat             ตราด   2869.424644
14              Chachoengsao       ฉะเชิงเทรา   5165.910411
15              Prachin Buri       ปราจีนบุรี   5046.991953
16              Nakhon Nayok          นครนายก   2136.473514
17                   Sa Kaeo          สระแก้ว   6788.908965
18         Nakhon Ratchasima       นครราชสีมา  20709.129379
19                  Buri Ram        บุรีรัมย์  10058.251514
20                     Surin         สุรินทร์   8815.660458
21                 Si Sa Ket         ศรีสะเกษ   8884.980063
22          Ubon Ratchathani      อุบลราชธานี  15482.814061
23                  Yasothon            ยโสธร   4097.293958
24                Chaiyaphum          ชัยภูมิ  12615.756015
25             Amnat Charoen       อำนาจเจริญ   3262.571368
26                 Bueng Kan           บึงกาฬ   3991.221379
27          Nong Bua Lam Phu      หนองบัวลำภู   4064.126376
28                 Khon Kaen          ขอนแก่น  10612.202446
29                Udon Thani         อุดรธานี  11054.261328
30                      Loei              เลย  10503.181724
31                 Nong Khai          หนองคาย   3271.149204
32             Maha Sarakham        มหาสารคาม   5607.557625
33                    Roi Et         ร้อยเอ็ด   7819.053663
34                   Kalasin        กาฬสินธุ์   6888.070231
35              Sakon Nakhon           สกลนคร   9526.968864
36             Nakhon Phanom           นครพนม   5585.723559
37                  Mukdahan         มุกดาหาร   4111.206259
38                Chiang Mai        เชียงใหม่  22176.037103
39                   Lamphun            ลำพูน   4482.900029
40                   Lampang            ลำปาง  12496.449201
41                 Uttaradit        อุตรดิตถ์   7919.274810
42                     Phrae             แพร่   6488.019856
43                       Nan             น่าน  12190.705498
44                    Phayao            พะเยา   6195.606609
45                Chiang Rai         เชียงราย  11584.266449
46              Mae Hong Son       แม่ฮ่องสอน  12771.977613
47              Nakhon Sawan        นครสวรรค์   9513.303173
48               Uthai Thani        อุทัยธานี   6638.454694
49            Kamphaeng Phet        กำแพงเพชร   8557.992477
50                       Tak              ตาก  17279.668009
51                 Sukhothai          สุโขทัย   6680.174061
52               Phitsanulok         พิษณุโลก  10523.255004
53                   Phichit           พิจิตร   4336.405165
54                Phetchabun        เพชรบูรณ์  12388.984479
55                Ratchaburi          ราชบุรี   5202.252245
56              Kanchanaburi        กาญจนบุรี  19450.911388
57               Suphan Buri       สุพรรณบุรี   5433.457336
58             Nakhon Pathom           นครปฐม   2139.199174
59              Samut Sakhon        สมุทรสาคร    856.875513
60           Samut Songkhram      สมุทรสงคราม    414.390807
61               Phetchaburi         เพชรบุรี   6183.000804
62       Prachuap Khiri Khan  ประจวบคีรีขันธ์   6448.389536
63       Nakhon Si Thammarat    นครศรีธรรมราช   9901.712714
64                     Krabi           กระบี่   4988.355388
65                  Phangnga            พังงา   4095.731358
66                    Phuket           ภูเก็ต    548.025456
67               Surat Thani     สุราษฎร์ธานี  13085.453392
68                    Ranong            ระนอง   3293.485117
69                  Chumphon            ชุมพร   6021.565231
70                  Songkhla            สงขลา   7741.350404
71                     Satun             สตูล   2881.574144
72                     Trang             ตรัง   4709.743170
73               Phatthalung           พัทลุง   3860.383277
74                   Pattani          ปัตตานี   1966.320520
75                      Yala             ยะลา   4472.740198
76                Narathiwat         นราธิวาส   4487.557450

In [19]:
df_adminid = pd.read_csv("../../data/Wild_Fire/Cumulative Fire Alerts in Thailand/adm1_metadata.csv")
df_adminid

                        name  adm1__id
0              Amnat Charoen         1
1                  Ang Thong         2
2         Bangkok Metropolis         3
3                  Bueng Kan         4
4                   Buri Ram         5
5               Chachoengsao         6
6                   Chai Nat         7
7                 Chaiyaphum         8
8                Chanthaburi         9
9                 Chiang Mai        10
10                Chiang Rai        11
11                 Chon Buri        12
12                  Chumphon        13
13                   Kalasin        14
14            Kamphaeng Phet        15
15              Kanchanaburi        16
16                 Khon Kaen        17
17                     Krabi        18
18                   Lampang        19
19                   Lamphun        20
20                      Loei        21
21                  Lop Buri        22
22              Mae Hong Son        23
23             Maha Sarakham        24
24                  Mukdahan        25
25              Nakhon Nayok        26
26             Nakhon Pathom        27
27             Nakhon Phanom        28
28         Nakhon Ratchasima        29
29              Nakhon Sawan        30
30       Nakhon Si Thammarat        31
31                       Nan        32
32                Narathiwat        33
33          Nong Bua Lam Phu        34
34                 Nong Khai        35
35                Nonthaburi        36
36              Pathum Thani        37
37                   Pattani        38
38                  Phangnga        39
39               Phatthalung        40
40                    Phayao        41
41                Phetchabun        42
42               Phetchaburi        43
43                   Phichit        44
44               Phitsanulok        45
45  Phra Nakhon Si Ayutthaya        46
46                     Phrae        47
47                    Phuket        48
48              Prachin Buri        49
49       Prachuap Khiri Khan        50
50                    Ranong        51
51                Ratchaburi        52
52                    Rayong        53
53                    Roi Et        54
54                   Sa Kaeo        55
55              Sakon Nakhon        56
56              Samut Prakan        57
57              Samut Sakhon        58
58           Samut Songkhram        59
59                  Saraburi        60
60                     Satun        61
61                 Si Sa Ket        62
62                 Sing Buri        63
63                  Songkhla        64
64                 Sukhothai        65
65               Suphan Buri        66
66               Surat Thani        67
67                     Surin        68
68                       Tak        69
69                     Trang        70
70                      Trat        71
71          Ubon Ratchathani        72
72                Udon Thani        73
73               Uthai Thani        74
74                 Uttaradit        75
75                      Yala        76
76                  Yasothon        77

In [20]:
# Map 'adm1__id' from df_adminid to df_check based on 'English_name'
df_check['adm1_id'] = df_check['English_name'].map(df_adminid.set_index('name')['adm1__id'])

# Verify the mapping
df_check['adm1_id'] == df_adminid.set_index('name').loc[df_check['English_name'], 'adm1__id'].values

df_check[['English_name', 'adm1_id']]

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/374992257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['adm1_id'] = df_check['English_name'].map(df_adminid.set_index('name')['adm1__id'])

                English_name  adm1_id
0         Bangkok Metropolis        3
1               Samut Prakan       57
2                 Nonthaburi       36
3               Pathum Thani       37
4   Phra Nakhon Si Ayutthaya       46
5                  Ang Thong        2
6                   Lop Buri       22
7                  Sing Buri       63
8                   Chai Nat        7
9                   Saraburi       60
10                 Chon Buri       12
11                    Rayong       53
12               Chanthaburi        9
13                      Trat       71
14              Chachoengsao        6
15              Prachin Buri       49
16              Nakhon Nayok       26
17                   Sa Kaeo       55
18         Nakhon Ratchasima       29
19                  Buri Ram        5
20                     Surin       68
21                 Si Sa Ket       62
22          Ubon Ratchathani       72
23                  Yasothon       77
24                Chaiyaphum        8
25             Amnat Charoen        1
26                 Bueng Kan        4
27          Nong Bua Lam Phu       34
28                 Khon Kaen       17
29                Udon Thani       73
30                      Loei       21
31                 Nong Khai       35
32             Maha Sarakham       24
33                    Roi Et       54
34                   Kalasin       14
35              Sakon Nakhon       56
36             Nakhon Phanom       28
37                  Mukdahan       25
38                Chiang Mai       10
39                   Lamphun       20
40                   Lampang       19
41                 Uttaradit       75
42                     Phrae       47
43                       Nan       32
44                    Phayao       41
45                Chiang Rai       11
46              Mae Hong Son       23
47              Nakhon Sawan       30
48               Uthai Thani       74
49            Kamphaeng Phet       15
50                       Tak       69
51                 Sukhothai       65
52               Phitsanulok       45
53                   Phichit       44
54                Phetchabun       42
55                Ratchaburi       52
56              Kanchanaburi       16
57               Suphan Buri       66
58             Nakhon Pathom       27
59              Samut Sakhon       58
60           Samut Songkhram       59
61               Phetchaburi       43
62       Prachuap Khiri Khan       50
63       Nakhon Si Thammarat       31
64                     Krabi       18
65                  Phangnga       39
66                    Phuket       48
67               Surat Thani       67
68                    Ranong       51
69                  Chumphon       13
70                  Songkhla       64
71                     Satun       61
72                     Trang       70
73               Phatthalung       40
74                   Pattani       38
75                      Yala       76
76                Narathiwat       33

In [21]:
pd.set_option('display.max_rows', None)

df_check.sort_values('adm1_id', inplace=True)
print(df_check)

#reset display options as default
pd.reset_option('display.max_rows')

                English_name        Thai_name          AREA  adm1_id
25             Amnat Charoen       อำนาจเจริญ   3262.571368        1
5                  Ang Thong          อ่างทอง    944.216921        2
0         Bangkok Metropolis    กรุงเทพมหานคร   1571.371336        3
26                 Bueng Kan           บึงกาฬ   3991.221379        4
19                  Buri Ram        บุรีรัมย์  10058.251514        5
14              Chachoengsao       ฉะเชิงเทรา   5165.910411        6
8                   Chai Nat           ชัยนาท   2486.567838        7
24                Chaiyaphum          ชัยภูมิ  12615.756015        8
12               Chanthaburi         จันทบุรี   6403.634178        9
38                Chiang Mai        เชียงใหม่  22176.037103       10
45                Chiang Rai         เชียงราย  11584.266449       11
10                 Chon Buri           ชลบุรี   4504.763605       12
69                  Chumphon            ชุมพร   6021.565231       13
34                   Kalasin        กาฬสินธุ์   6888.070231       14
49            Kamphaeng Phet        กำแพงเพชร   8557.992477       15
56              Kanchanaburi        กาญจนบุรี  19450.911388       16
28                 Khon Kaen          ขอนแก่น  10612.202446       17
64                     Krabi           กระบี่   4988.355388       18
40                   Lampang            ลำปาง  12496.449201       19
39                   Lamphun            ลำพูน   4482.900029       20
30                      Loei              เลย  10503.181724       21
6                   Lop Buri           ลพบุรี   6491.816312       22
46              Mae Hong Son       แม่ฮ่องสอน  12771.977613       23
32             Maha Sarakham        มหาสารคาม   5607.557625       24
37                  Mukdahan         มุกดาหาร   4111.206259       25
16              Nakhon Nayok          นครนายก   2136.473514       26
58             Nakhon Pathom           นครปฐม   2139.199174       27
36             Nakhon Phanom           นครพนม   5585.723559       28
18         Nakhon Ratchasima       นครราชสีมา  20709.129379       29
47              Nakhon Sawan        นครสวรรค์   9513.303173       30
63       Nakhon Si Thammarat    นครศรีธรรมราช   9901.712714       31
43                       Nan             น่าน  12190.705498       32
76                Narathiwat         นราธิวาส   4487.557450       33
27          Nong Bua Lam Phu      หนองบัวลำภู   4064.126376       34
31                 Nong Khai          หนองคาย   3271.149204       35
2                 Nonthaburi          นนทบุรี    636.542920       36
3               Pathum Thani         ปทุมธานี   1517.386645       37
74                   Pattani          ปัตตานี   1966.320520       38
65                  Phangnga            พังงา   4095.731358       39
73               Phatthalung           พัทลุง   3860.383277       40
44                    Phayao            พะเยา   6195.606609       41
54                Phetchabun        เพชรบูรณ์  12388.984479       42
61               Phetchaburi         เพชรบุรี   6183.000804       43
53                   Phichit           พิจิตร   4336.405165       44
52               Phitsanulok         พิษณุโลก  10523.255004       45
4   Phra Nakhon Si Ayutthaya  พระนครศรีอยุธยา   2553.360962       46
42                     Phrae             แพร่   6488.019856       47
66                    Phuket           ภูเก็ต    548.025456       48
15              Prachin Buri       ปราจีนบุรี   5046.991953       49
62       Prachuap Khiri Khan  ประจวบคีรีขันธ์   6448.389536       50
68                    Ranong            ระนอง   3293.485117       51
55                Ratchaburi          ราชบุรี   5202.252245       52
11                    Rayong            ระยอง   3682.137154       53
33                    Roi Et         ร้อยเอ็ด   7819.053663       54
17                   Sa Kaeo          สระแก้ว   6788.908965       55
35              Sakon Nakhon           สกลนคร   9526.968864       56
1               Samut Prakan      สมุทรปราการ    949.001113       57
59              Samut Sakhon        สมุทรสาคร    856.875513       58
60           Samut Songkhram      สมุทรสงคราม    414.390807       59
9                   Saraburi          สระบุรี   3481.759648       60
71                     Satun             สตูล   2881.574144       61
21                 Si Sa Ket         ศรีสะเกษ   8884.980063       62
7                  Sing Buri        สิงห์บุรี    818.192131       63
70                  Songkhla            สงขลา   7741.350404       64
51                 Sukhothai          สุโขทัย   6680.174061       65
57               Suphan Buri       สุพรรณบุรี   5433.457336       66
67               Surat Thani     สุราษฎร์ธานี  13085.453392       67
20                     Surin         สุรินทร์   8815.660458       68
50                       Tak              ตาก  17279.668009       69
72                     Trang             ตรัง   4709.743170       70
13                      Trat             ตราด   2869.424644       71
22          Ubon Ratchathani      อุบลราชธานี  15482.814061       72
29                Udon Thani         อุดรธานี  11054.261328       73
48               Uthai Thani        อุทัยธานี   6638.454694       74
41                 Uttaradit        อุตรดิตถ์   7919.274810       75
75                      Yala             ยะลา   4472.740198       76
23                  Yasothon            ยโสธร   4097.293958       77

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/598184385.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check.sort_values('adm1_id', inplace=True)

In [22]:
data = pd.read_json("data.json")

# If you need to skip the first row, you can drop it after loading the data
data = data.iloc[0:]

In [23]:
data

                 0         1          2
0         Location  Latitude  Longitude
1    Amnat Charoen   15°51'N   104°38'E
2        Ang Thong   14°35'N   100°31'E
3    Aranyaprathet   13°41'N   102°30'E
4     Ban Bang Hin   09°32'N    98°35'E
..             ...       ...        ...
131        Lom Sak   16°47'N   101°15'E
132       Lop Buri   14°48'N   100°37'E
133   Luang, Thale   07°30'N   100°15'E
134       Mae Chan   20°09'N    99°52'E
135   Mae Hong Son   19°16'N    97°56'E

[136 rows x 3 columns]

In [24]:
#index 0 is column names
data.columns = data.iloc[0]
data = data[1:]
data.reset_index(drop=True, inplace=True)

data

0            Location Latitude Longitude
0       Amnat Charoen  15°51'N  104°38'E
1           Ang Thong  14°35'N  100°31'E
2       Aranyaprathet  13°41'N  102°30'E
3        Ban Bang Hin  09°32'N   98°35'E
4    Ban Chiang Klang  19°25'N  100°55'E
..                ...      ...       ...
130           Lom Sak  16°47'N  101°15'E
131          Lop Buri  14°48'N  100°37'E
132      Luang, Thale  07°30'N  100°15'E
133          Mae Chan  20°09'N   99°52'E
134      Mae Hong Son  19°16'N   97°56'E

[135 rows x 3 columns]

In [25]:
# Check if the 'Location' column in 'data' matches any province in 'df_check["English_name"]'
data['is_province'] = data['Location'].isin(df_check['English_name'])

# Display the rows where 'is_province' is True
data[data['is_province']]

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/3280862945.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['is_province'] = data['Location'].isin(df_check['English_name'])

0          Location Latitude Longitude  is_province
0     Amnat Charoen  15°51'N  104°38'E         True
1         Ang Thong  14°35'N  100°31'E         True
52     Chachoengsao  13°42'N  101°05'E         True
60      Chanthaburi  12°38'N  102°12'E         True
70       Chiang Mai  18°47'N   98°59'E         True
71       Chiang Rai  19°52'N   99°50'E         True
76        Chon Buri  13°21'N  101°01'E         True
80         Chumphon  10°35'N   99°14'E         True
95          Kalasin  16°26'N  103°30'E         True
96   Kamphaeng Phet  16°28'N   99°30'E         True
98     Kanchanaburi  14°02'N   99°31'E         True
105       Khon Kaen  16°30'N  102°47'E         True
114           Krabi  08°04'N   98°55'E         True
122         Lampang  18°16'N   99°32'E         True
128            Loei  17°29'N  101°35'E         True
131        Lop Buri  14°48'N  100°37'E         True
134    Mae Hong Son  19°16'N   97°56'E         True

In [28]:
df_provinces = pd.read_csv("../../data/boundaries/provinces.csv")
df_provinces

    province_id  province_name  province_lat  province_lon  province_zoom
0             1  กรุงเทพมหานคร     13.727896    100.524123             13
1             2         กระบี่      8.086300     98.906283             13
2             3      กาญจนบุรี     14.022780     99.532811             13
3             4      กาฬสินธุ์     16.431408    103.505876             13
4             5      กำแพงเพชร     16.482780     99.522662             13
..          ...            ...           ...           ...            ...
72           73       อุดรธานี     17.413841    102.787233             13
73           74      อุตรดิตถ์     17.620089    100.099294             13
74           75      อุทัยธานี     15.383500    100.024553             13
75           76    อุบลราชธานี     15.228686    104.856422             13
76           77         บึงกาฬ     18.360910    103.646446             13

[77 rows x 5 columns]

In [29]:
df_provinces['is_province'] = df_provinces['province_name'].isin(df_check['Thai_name'])
df_provinces[df_provinces['is_province']]

,province_id,province_name,province_lat,province_lon,province_zoom,is_province
0,1,กรุงเทพมหานคร,13.727896,100.524123,13,True
1,2,กระบี่,8.086300,98.906283,13,True
2,3,กาญจนบุรี,14.022780,99.532811,13,True
3,4,กาฬสินธุ์,16.431408,103.505876,13,True
4,5,กำแพงเพชร,16.482780,99.522662,13,True
...,...,...,...,...,...,...
72,73,อุดรธานี,17.413841,102.787233,13,True
73,74,อุตรดิตถ์,17.620089,100.099294,13,True
74,75,อุทัยธานี,15.383500,100.024553,13,True
75,76,อุบลราชธานี,15.228686,104.856422,13,True
76,77,บึงกาฬ,18.360910,103.646446,13,True

In [30]:
# กทม
# เชียงใหม่
# กาญ
# ขอนแก่น
# ภูเก็ต
# ชลบุรี

df_use = df_provinces[df_provinces['province_name'].isin(["กรุงเทพมหานคร", "เชียงใหม่", "กาญจนบุรี", "ขอนแก่น", "ภูเก็ต", "ชลบุรี"])]

In [31]:
df_use

,province_id,province_name,province_lat,province_lon,province_zoom,is_province
0,1,กรุงเทพมหานคร,13.727896,100.524123,13,True
2,3,กาญจนบุรี,14.022780,99.532811,13,True
5,6,ขอนแก่น,16.441935,102.835992,13,True
8,9,ชลบุรี,13.361143,100.984672,13,True
13,14,เชียงใหม่,18.787748,98.993131,13,True
40,41,ภูเก็ต,7.981050,98.363882,13,True

In [32]:
df_use.drop(columns=['province_id', 'province_zoom', 'is_province'], inplace=True)

/var/folders/yz/zvlp09kd3l12735_165qzk0c0000gn/T/ipykernel_79359/4223902965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_use.drop(columns=['province_id', 'province_zoom', 'is_province'], inplace=True)

In [33]:
df_use.reset_index(drop=True, inplace=True)

In [34]:
df_use

   province_name  province_lat  province_lon
0  กรุงเทพมหานคร     13.727896    100.524123
1      กาญจนบุรี     14.022780     99.532811
2        ขอนแก่น     16.441935    102.835992
3         ชลบุรี     13.361143    100.984672
4      เชียงใหม่     18.787748     98.993131
5         ภูเก็ต      7.981050     98.363882

In [35]:
df_use = df_use.merge(df_check, left_on='province_name', right_on='Thai_name', how='left')

In [36]:
df_use

,province_name,province_lat,province_lon,English_name,Thai_name,AREA,adm1_id
0,กรุงเทพมหานคร,13.727896,100.524123,Bangkok Metropolis,กรุงเทพมหานคร,1571.371336,3
1,กาญจนบุรี,14.022780,99.532811,Kanchanaburi,กาญจนบุรี,19450.911388,16
2,ขอนแก่น,16.441935,102.835992,Khon Kaen,ขอนแก่น,10612.202446,17
3,ชลบุรี,13.361143,100.984672,Chon Buri,ชลบุรี,4504.763605,12
4,เชียงใหม่,18.787748,98.993131,Chiang Mai,เชียงใหม่,22176.037103,10
5,ภูเก็ต,7.981050,98.363882,Phuket,ภูเก็ต,548.025456,48

In [37]:
df_use.drop(columns=['adm1_id', 'Thai_name'], inplace=True)

In [38]:
df_use

   province_name  province_lat  province_lon        English_name          AREA
0  กรุงเทพมหานคร     13.727896    100.524123  Bangkok Metropolis   1571.371336
1      กาญจนบุรี     14.022780     99.532811        Kanchanaburi  19450.911388
2        ขอนแก่น     16.441935    102.835992           Khon Kaen  10612.202446
3         ชลบุรี     13.361143    100.984672           Chon Buri   4504.763605
4      เชียงใหม่     18.787748     98.993131          Chiang Mai  22176.037103
5         ภูเก็ต      7.981050     98.363882              Phuket    548.025456

In [43]:
df_use.to_csv("../../data/a1/indicator.csv", index=False)

In [40]:
df_pmmap.drop(columns=['จังหวัด', 'adm1__id'], inplace=True)

In [41]:
df_pmmap

,รหัสสถานี,ชื่อสถานี,รายละเอียดจุดติดตั้งสถานี,english_name
0,02T,แขวงหิรัญรูจี เขตธนบุรี กทม.,มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา,Bangkok Metropolis
1,05T,แขวงบางนา เขตบางนา กทม.,กรมอุตุนิยมวิทยา,Bangkok Metropolis
2,10T,แขวงคลองจั่น เขตบางกะปิ กทม.,เคหะชุมชนคลองจั่น,Bangkok Metropolis
3,11T,แขวงดินแดง เขตดินแดง กทม.,สนามกีฬาเคหะชุมชนห้วยขวาง,Bangkok Metropolis
4,12T,แขวงช่องนนทรี เขตยานนาวา กทม.,โรงเรียนนนทรีวิทยา,Bangkok Metropolis
...,...,...,...,...
91,63T,ต.สะเตง อ.เมือง จ.ยะลา,สวนสาธารณะสนามโรงพิธีช้างเผือก ยะลา,Yala
92,78T,ต.เบตง อ.เบตง จ.ยะลา,ศูนย์พัฒนาเด็กเล็กเทศบาลเมืองเบตง,Yala
93,80T,ต.พิมาน อ.เมือง. จ.สตูล,ศาลากลางจังหวัดสตูล,Satun
94,89T,ต.คลัง อ.เมือง จ.นครศรีธรรมราช,ศูนย์ฟื้นฟูสุขภาพผู้สูงอายุ,Nakhon Si Thammarat
95,93T,ต.นาตาล่วง อ.เมืองตรัง จ.ตรัง,วิทยาลัยสารพัดช่างตรัง,Trang

In [ ]:
df_pmmap.to_csv("../../data/a1/PM_map.csv", index=False)